### ISSUE TITLE
UI Correction for Login and Sign Up

### ISSUE THREAD

**Issue by amit429** [MAVRICK-1/e-commerce_website#100]
**Describe the bug**
For the Login and sign up pages the form UI is not very neat and clean. The place holder is going out of the box and its not even responsive. Both login and sign up forms have UI issues which need to be addressed immediately for good user experience.

**To Reproduce**

1. Go to 'Home Page'
2. Click on 'Sign In'
3. See error

**Expected behavior**
The UI of the form should be clean and user friendly.

**Screenshots**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/68067897/9d6b42a4-1fea-4656-aca0-f8b8e8fe7155)

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/68067897/a203632d-f3d2-437c-9528-3c1227622998)

This UI issue needs to be fixed

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]
- Version [11]

**Additional Comments**
I am a GSSOC'24 contributor , i would like to take up this issue and correct it. Could you please assign me this issue under the label GSSOC'24

**Comment by amit429** [comment]
@MAVRICK-1 Can you please assign me this issue under the gssoc'24 tag

**Comment by MAVRICK-1** [comment]
#87 duplicate issue
