### ISSUE TITLE
[Feature] :want to add a Contact Us from and implement the faciality to automatically sent message to the owner's email when the user is submitted the message

### ISSUE THREAD

**Issue by AnitSarkar123** [MAVRICK-1/e-commerce_website#103]
**Is your feature request related to a problem? Please describe.**
contact us page is not present

**Describe the solution you'd like**
make it responsive and use email.js

**Describe alternatives you've considered**
none

please assign me under GSSOC'24

**Comment by MAVRICK-1** [comment]
@AnitSarkar123 will be back on this after few changes

**Comment by AnitSarkar123** [comment]
@MAVRICK-1 why you close this
