### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [MAVRICK-1/e-commerce_website#105]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email**.

**Describe the solution you'd like**
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Describe alternatives you've considered**

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by MAVRICK-1** [comment]
@pankaj-bind solve this #87 first , then i will assign you
