### ISSUE TITLE
Styling of the proceed to check out box

### ISSUE THREAD

**Issue by Hemu21** [MAVRICK-1/e-commerce_website#108]
**Describe the bug**
The styling of the proceed to check out box is not well organisied.

**To Reproduce**

1. Go to cart or wishlist
2. check the procedd to check out box.

**Expected behavior**
proceed to check out box is well organized.

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this to me. please add labels.

**Comment by MAVRICK-1** [comment]
@Hemu21 okay go ahead

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please check my pr.
