### ISSUE TITLE
Add Wishlist Page Link

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#110]
# Add Wishlist Page Link

**Description:**

**Issue**
Currently, there's no direct link to access the wishlist page from the wishlist text.

**Proposal**
Add a hyperlink within the wishlist text, leading users to their wishlist page for easy navigation.

<img width="159" alt="Screenshot 2024-05-14 005328" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/31cc9753-80ae-44ea-ade3-75245e7ba43c">

**Implementation**
- **Location:** Insert hyperlink in the wishlist text.
- **Hyperlink Text:** Decide on text like "View Wishlist".
- **Link Destination:** Set the link to the wishlist page.

### will be assigned only to beginners

**Comment by Bhanuteja01** [comment]
@MAVRICK-1  assign me  this issue 
i'm gssoc contributor

**Comment by MAVRICK-1** [comment]
@Bhanuteja01 it's only for beginners

**Comment by Varsani2520** [comment]
can you assigned this issue @MAVRICK-1

**Comment by KhushiSahu0108** [comment]
Please assign this issue to me.
