### ISSUE TITLE
Problem in add to cart and wishlist section

### ISSUE THREAD

**Issue by Priyapandeyyy** [MAVRICK-1/e-commerce_website#111]
**Describe the bug**
There is a problem in the Add to Cart and wishlist sections. I am not able to put my items in the cart or like add in the wishlist section.

![Screenshot 2024-05-14 011042](https://github.com/MAVRICK-1/e-commerce_website/assets/132647631/7ce46f0c-b8fc-479d-a2e7-381d06d25b18)

**Comment by MAVRICK-1** [comment]
you have to login in first

**Comment by Priyapandeyyy** [comment]
Oh yeah. Thanks
