### ISSUE TITLE
feat: Validations are missing on the sign in page

### ISSUE THREAD

**Issue by Niharika0104** [MAVRICK-1/e-commerce_website#113]
**Is your feature request related to a problem? Please describe.**
I see that validations are missing on the sign in page.Adding validations will make it ui friendly and will not cause unneccessary call to the database as well will only call the method if the data entered in the form is valid.
**Currently the sign in button looks like the button is disabled but it's always good to have the validation messages.**

**Describe the solution you'd like**
I will use react-toastify library to show the validation errors.

**Describe alternatives you've considered**
I can also just provide the error message in the text format but ,the former method is more modern and ui friendly

**Comment by MAVRICK-1** [comment]
go ahead but follow the css hierarchy

**Comment by Niharika0104** [comment]
@MAVRICK-1 may I know why is this issue closed

**Comment by MAVRICK-1** [comment]
@Niharika0104 #44
