### ISSUE TITLE
Subscribe Functionality not working

### ISSUE THREAD

**Issue by amit429** [MAVRICK-1/e-commerce_website#117]
**Describe the Fuctionality**
On the home page the subscribe functionality is not working

**To Reproduce**

1. Go to 'Home'
2. Click on 'scroll down and type your email in subscribe'
3. Click on subscribe button

**Expected behavior**
When the subscribe button is hit , the email id should go to the backend where there is a model for subscriptions which takes the user email typed and the user id from the logged in user

**Screenshots**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/68067897/dffde060-2c49-4779-8d30-57e8ad81200d)

**Additional context**
Please assign me this issue under GSSOC'24 tag and levels

**Comment by amit429** [comment]
@MAVRICK-1 please assign me this issue

**Comment by MAVRICK-1** [comment]
@amit429 we haven't  implement the functionality till .

**Comment by amit429** [comment]
@MAVRICK-1 can you assign me that so I can implement it. I have edited the issue as a feature

**Comment by amit429** [comment]
@MAVRICK-1 I can take up the implementation of this

**Comment by MAVRICK-1** [comment]
@amit429 first tell me how will you implement this

**Comment by amit429** [comment]
@MAVRICK-1 We will need one more collection in the firebase to store all the subscriptions. We will be taking the provided email from the input box for the newsletter subscription along with the user name and other details to address the news letter.

**Comment by MAVRICK-1** [comment]
@amit429 that's a great idea but we don't need it
