### ISSUE TITLE
Following the issue #93 adding prettier to the project

### ISSUE THREAD

**Issue by AvdhutPailwan** [MAVRICK-1/e-commerce_website#120]
In #93 pre-commit hooks have been added but for consistent formatting adding prettier is necessary and configuring the prettier to work with lint-staged and pre-commit hooks

@MAVRICK-1 I would like to work on the this issue under gssoc

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan don't make a separate PR  for this include this in #118 , i will mark it level3

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan don't make a separate PR  for this include this in #118 , i will mark it level3

Okay

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan but i will check it after , 18 . won't be available for few days

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan but i will check it after , 18 . won't be available for few days

I am already done ✅
