### ISSUE TITLE
search functionality is not working

### ISSUE THREAD

**Issue by Varsani2520** [MAVRICK-1/e-commerce_website#124]
Hey @MAVRICK-1 
user click on search textfield for the search category then not display search data 

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/137641079/8cd39499-f1b2-4298-9c37-aa830ebb0e08)

**Comment by MAVRICK-1** [comment]
okay go ahead

**Comment by Varsani2520** [comment]
thank you @MAVRICK-1  ,for this oppertunity
i will give my best

**Comment by Varsani2520** [comment]
@MAVRICK-1 I am unable to find your backend folder...
can you please tell me where your all data come from ?

**Comment by Varsani2520** [comment]
okay @MAVRICK-1
