### ISSUE TITLE
social media buttons on footer not working

### ISSUE THREAD

**Issue by nagamukesh** [MAVRICK-1/e-commerce_website#126]
**Describe the bug**
The social media handles in the footer are not working properly

**To Reproduce**

1. Go to the main page
2. Scroll down to the bottom of the page
3. click on social media buttons

**Expected behavior**
one can be able to access the social media handles of the website

please assign this issue to me under gssoc 2024
I can fix it provided some social media handles

**Comment by MAVRICK-1** [comment]
for social media add  github handel and link that to this repo discussion , rest use my handels

**Comment by prachi-kurmi** [comment]
@MAVRICK-1 If he didn't work on this issue, could you assign it to me?

**Comment by nagamukesh** [comment]
@MAVRICK-1 can I get the handles/links for facebook, youtube and twitter/X 
I didn't find them

**Comment by MAVRICK-1** [comment]
@nagamukesh u don't have to give any links just change the logo
