### ISSUE TITLE
Creating Contact Page

### ISSUE THREAD

**Issue by UjjwalGupta1105** [MAVRICK-1/e-commerce_website#130]
In navbar, contact button is not working-:

![Contact_US_2 GSSOC](https://github.com/MAVRICK-1/e-commerce_website/assets/165131091/17c54d1a-9fed-4ed0-91c9-376265ee9ffa)

**SOLUTION**-:

I want to create a **contact page** ,like this-:

![Contact_US GSSOC](https://github.com/MAVRICK-1/e-commerce_website/assets/165131091/cf690c78-d390-4c1b-aa68-b3ef81a4cf45)

**Comment by MAVRICK-1** [comment]
@UjjwalGupta1105 duplicate issue #103
