### ISSUE TITLE
To Center the Featured Categories Section 

### ISSUE THREAD

**Issue by UjjwalGupta1105** [MAVRICK-1/e-commerce_website#131]
To move the **Featured Categories Section** in the middle

![Screenshot 2024-05-15 004830747](https://github.com/MAVRICK-1/e-commerce_website/assets/165131091/e5e907e2-f729-45b4-82d5-5f98ef9b552a)

**Comment by MAVRICK-1** [comment]
@UjjwalGupta1105 thanks for the issue but i like the above design
