### ISSUE TITLE
Creating About Page

### ISSUE THREAD

**Issue by UjjwalGupta1105** [MAVRICK-1/e-commerce_website#132]
The about button in Navbar is not working-:
![new2](https://github.com/MAVRICK-1/e-commerce_website/assets/165131091/49005294-0cce-42d6-a068-6635fe19492b)

**Solution-:**-:
I will create an **about page** for it by using the temporary details like this-:
![new1](https://github.com/MAVRICK-1/e-commerce_website/assets/165131091/e6e19a5e-a508-4669-afba-1d4f516258dd)

**Comment by MAVRICK-1** [comment]
@UjjwalGupta1105 about us page is already present scroll up   , instead of about details we get our contributors details
