### ISSUE TITLE
Slider Image width is cut 

### ISSUE THREAD

**Issue by Varsani2520** [MAVRICK-1/e-commerce_website#139]
in slider image is not display full inside the slider ,i think it has not full width of the image 
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/137641079/48951267-295d-4841-a12d-76b9a5b40198)

for this issue assigned me @MAVRICK-1

**Comment by MAVRICK-1** [comment]
@Varsani2520 it's responsive refresh the page
