### ISSUE TITLE
[Feat] :  Back to top Button 

### ISSUE THREAD

**Issue by Arghyadeep09** [MAVRICK-1/e-commerce_website#144]
Problem:

The absence of a back-to-top button on the website significantly impairs its user-friendliness and navigational convenience, posing a notable problem in terms of user experience

Actual Behavior :

The Back to top button is not present

Expected Behavior : 

There should be a back to top button

Screenshot :
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/90449806/fce4aede-5063-477b-acce-05fc7148dd6e)

**Comment by Arghyadeep09** [comment]
Under GSSOC 24, Please assign the work to me!

**Comment by MAVRICK-1** [comment]
@Arghyadeep09 okay go ahead , i will assign you level after your work

**Comment by Arghyadeep09** [comment]
ok

**Comment by Arghyadeep09** [comment]
@MAVRICK-1 I have done the task should i create a new PR first or you will assign to me first?

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/90449806/2b33ffb0-208b-46eb-a90c-7c276da63a2c)

**Comment by MAVRICK-1** [comment]
Create a PR

**Comment by MAVRICK-1** [comment]
@Arghyadeep09 create PR
