### ISSUE TITLE
bug: Image Optimization

### ISSUE THREAD

**Issue by SiddhiT28** [MAVRICK-1/e-commerce_website#149]
**Describe the bug**
The current image handling process is not optimizing image file sizes. The leads to larger files being loaded unnecessarily, which can significantly impact page load times and user experience

**Expected behaviour**
Images uploaded to the codebase should be optimized for the web. This typically involves techniques like lossless compression or conversion to WebP format, reducing file size without significant visual quality.

**Comment by SiddhiT28** [comment]
I'd like to work on this issue under GSSoC 24! I'm familiar with image optimization techniques and can help implement a solution to reduce file size without compromising quality.

**Comment by MAVRICK-1** [comment]
@SiddhiT28 okay go ahead i will level after reviewing your pr
