### ISSUE TITLE
Add functionality to Bowse all category button

### ISSUE THREAD

**Issue by Tanishasi** [MAVRICK-1/e-commerce_website#151]
**Is your feature request related to a problem? Please describe.**
add categories and sub categories

**Comment by MAVRICK-1** [comment]
@Tanishasi it's a duplicated issue #37 let's talk about this over there

**Comment by MAVRICK-1** [comment]
@Tanishasi go ahead, by bad

**Comment by Tanishasi** [comment]
okay thank you!
