### ISSUE TITLE
Implementation of Dark/Light Mode Toggle

### ISSUE THREAD

**Issue by thevijayshankersharma** [MAVRICK-1/e-commerce_website#152]
**Is your feature request related to a problem? Please describe.**
Currently, the absence of a dark/light mode toggle limits user customization options and may lead to discomfort during prolonged usage, especially in low-light environments.

**Describe the solution you'd like**
I would like to implement a toggle switch within the application interface, allowing users to seamlessly switch between dark and light modes. Dark mode should feature darker color schemes for improved readability and reduced eye strain.

**Describe alternatives you've considered**
An alternative approach could involve providing predefined themes with dark and light mode options. However, a toggle switch offers a more intuitive and user-friendly solution.

**Additional context**
The addition of a dark/light mode toggle aligns with modern design trends and user preferences for customizable interfaces. It enhances user satisfaction and usability by providing a personalized browsing experience tailored to individual preferences.

**Comment by ratnesh-maurya** [comment]
Sure Go Ahead @thevijayshankersharma

**Comment by MAVRICK-1** [comment]
@thevijayshankersharma @ratnesh-maurya this issue has already been raised #1 , @thevijayshankersharma and @ira-mane you guys can divide the work among yourself

**Comment by thevijayshankersharma** [comment]
@MAVRICK-1 But he hasn't done anything till now. I think it would be great if you let me solve this issue.

**Comment by thevijayshankersharma** [comment]
@ira-mane Hey are you doing this issue or should I complete it ?
@MAVRICK-1 @ratnesh-maurya What should I do now if he/she doesn't reply ?

**Comment by thevijayshankersharma** [comment]
@MAVRICK-1 @ratnesh-maurya  Now??

**Comment by MAVRICK-1** [comment]
@thevijayshankersharma okay ho ahead

**Comment by thevijayshankersharma** [comment]
Could you add level ?

**Comment by MAVRICK-1** [comment]
@thevijayshankersharma you can divide it into 2 parts each level 3

**Comment by Ayushmaanagarwal1211** [comment]
@MAVRICK-1  Can i work on that

**Comment by GOURAVSINGH19** [comment]
@MAVRICK-1  can I work on that..
