### ISSUE TITLE
Modify Contributor card  

### ISSUE THREAD

**Issue by root-0101** [MAVRICK-1/e-commerce_website#156]
- The size of contributor cards are uneven and, also adding some hover effect to the card make the page more engaging for users

![Screenshot 2024-05-17 002842](https://github.com/MAVRICK-1/e-commerce_website/assets/142779809/f3e53bd8-060d-4eb5-a100-4fcaae59d868)

**Comment by anujsingh4545** [comment]
I would like to work on this issue, pls assign it to me .

**Comment by MAVRICK-1** [comment]
<img width="593" alt="Screenshot 2024-05-17 220753" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/be1b2bae-73aa-4ac0-bbef-65b0522c39a1">
@root-0101 make it like this , i will give you level after seeing ur PR

**Comment by root-0101** [comment]
Ok got it, Thanks for assigning me,
I will work on this issue and soon raise my PR

**Comment by root-0101** [comment]
- I have done with the changes and make the contributors card as you instructed in above conversation please check the PR #167
