### ISSUE TITLE
replacing product title and image

### ISSUE THREAD

**Issue by sahithinandikula** [MAVRICK-1/e-commerce_website#158]
**Is your feature request related to a problem? Please describe.**
The products in the  image below are similar, I Can change them to some other items

**Describe the solution you'd like**
We can replace them with other products and add their respective image

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/138794574/fb396de1-9f7b-47dd-8310-b930788e9b73)

**Comment by sahithinandikula** [comment]
@MAVRICK-1 I am looking forward to contributing to the project.

**Comment by MAVRICK-1** [comment]
@sahithinandikula we don't have any demo picture till now
