### ISSUE TITLE
Adding a scroll back to top button

### ISSUE THREAD

**Issue by sahithinandikula** [MAVRICK-1/e-commerce_website#159]
**Is your feature request related to a problem? Please describe.**
the website lacks a scroll back to the top button.

**Describe the solution you'd like**
A scroll back to the top button can enhance the user experience.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/138794574/19214048-f0c1-4f8a-89b3-c56319a638a6)

.

**Comment by sahithinandikula** [comment]
@MAVRICK-1 looking forward to contribute , please assign the issue and label it

**Comment by Hemu21** [comment]
@sahithinandikula  this issue is already raised and solved by someone else. currently code is merging to dev the deployed one is main so the changes are not reflection. to find issues please setup the project in localhost. here is the merged PR #148
