### ISSUE TITLE
Browse all categories drop down is not working.

### ISSUE THREAD

**Issue by SaiSathvik6** [MAVRICK-1/e-commerce_website#161]
**Describe the bug**
On the landing webpage when we click on browse all categories the drop-down is not working.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to the landing page of the website
2. Click on browse all categories
3. See error

**Expected behaviour**
when we click on Browse all categories it should show all the available categories on the website. as similar to other dropdowns.

**Desktop (please complete the following information):**
- Browser: Chrome

**Comment by MAVRICK-1** [comment]
@SaiSathvik6 duplicate issue #151
