### ISSUE TITLE
Website is not Responsive on Mobile Sizes.

### ISSUE THREAD

**Issue by shrutigolwalk0109** [MAVRICK-1/e-commerce_website#162]
Can you assign me this Task with the label of GSSOC, As I can make the website responsive on mobile sizes as well for a better user interface .

Screenshot :-
![WhatsApp Image 2024-05-17 at 21 42 51_8f6f0e66](https://github.com/MAVRICK-1/e-commerce_website/assets/132553685/b9e6c392-7511-4da6-81fb-402a4430a2a0)
![WhatsApp Image 2024-05-17 at 21 42 51_b2538b51](https://github.com/MAVRICK-1/e-commerce_website/assets/132553685/a3fc99e1-ac02-4713-adf2-61d17f42cd0a)

**Comment by MAVRICK-1** [comment]
@shrutigolwalk0109 refresh it .
