### ISSUE TITLE
Shop now buttons are just images

### ISSUE THREAD

**Issue by ananya-sh30** [MAVRICK-1/e-commerce_website#163]
Reference:
 
![Screenshot 2024-05-17 234009](https://github.com/MAVRICK-1/e-commerce_website/assets/142817946/4bdf19ab-4a37-42cc-b7c4-f6c108d0c9dd)

**Is your feature request related to a problem? Please describe.**
In the above section the shop now buttons are included in the image itself and are not actual buttons.

**Describe the solution you'd like**
I would like to make them actual buttons and improve/change these images in the background. 

Please consider assigning this issue to me along with gssoc labels.

**Comment by MAVRICK-1** [comment]
@ananya-sh30  it's just for design purpose we don't have that product
