### ISSUE TITLE
[DOCS]: Write Installation Guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [MAVRICK-1/e-commerce_website#165]
Describe the changes that you want to make in the documentation
Draft a comprehensive guide that outlines the step-by-step process for installing and setting up Nest ONDC Project locally on different operating systems (Windows, macOS, Linux).

Significance of the changes made
By providing clear installation instructions, we can lower the barrier for new users to get started with Draw-it-out, encouraging wider adoption of the application.

And also I'm excited to contribute to the Nest ONDC project. Could you please assign me.

Thank You @MAVRICK-1

**Comment by MAVRICK-1** [comment]
@iamkanhaiyakumar it's already given in readme file
