### ISSUE TITLE
Bug: My Wish list link is not working.

### ISSUE THREAD

**Issue by abhiperfect** [MAVRICK-1/e-commerce_website#169]
**Describe the bug**
My Wish list link is not working.

**Expected behavior**
Redirect to the wishlist section.

**Screenshots**
![Screenshot 2024-05-18 022627](https://github.com/MAVRICK-1/e-commerce_website/assets/114478676/29b8ae6c-cfbf-4d7c-a38e-bb9e23fbf584)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by MAVRICK-1** [comment]
@abhiperfect duplicate issue #110
