### ISSUE TITLE
Feat: [Frontend] My Account page where user can change email, name and password.

### ISSUE THREAD

**Issue by abhiperfect** [MAVRICK-1/e-commerce_website#170]
Feature: Implementing a "My Account" page allowing users to modify their email, name, and password, enhancing user control and customization within the platform.

**Describe the solution you'd like**
The solution entails creating a dedicated "My Account" page accessible to users. On this page, users can find forms or fields to input and update their email address, name, and password. Each field should be accompanied by appropriate validation to ensure data integrity and security. 

**Describe alternatives you've considered**
One option is to integrate account management directly into user profiles, streamlining the process. This consolidates actions such as updating email, name, and password within the profile settings for a seamless user experience.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by MAVRICK-1** [comment]
@abhiperfect all functionality are already added .
