### ISSUE TITLE
Feat: [Backend] My Account page where user can change email, name and password.

### ISSUE THREAD

**Issue by abhiperfect** [MAVRICK-1/e-commerce_website#171]
**Is your feature request related to a problem? Please describe.**
Feature: Implementing backend functionality for a "My Account" page, enabling users to update their email, name, and password, enhancing user control and customization within the platform.

**Describe the solution you'd like**
The solution entails implementing secure API endpoints in the backend for users to update their email, name, and password. This involves authentication, data validation, and database updates, ensuring data integrity and security.

**Comment by abhiperfect** [comment]
I would like to work on this issue.

**Comment by MAVRICK-1** [comment]
@abhiperfect we already got everything, and change email functionality is not available because it is the primary key.
