### ISSUE TITLE
Add Form Control to Sign-in and Sign-up Pages

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#18]
# Add Form Control to[ Sign-in](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/SignIn) and [Sign-up](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/SignUp) Pages

<img width="959" alt="Screenshot 2024-05-11 001014" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/52a88654-4613-47cf-866c-d4188ab90e15">

## Description
To enhance user experience and ensure data integrity, I propose adding form control to the sign-in and sign-up pages of our application. With this enhancement, the submit buttons will remain disabled until the required fields receive input values.

## Key Points
- **Sign-in Page:** Add form control to the sign-in page.
- **Sign-up Page:** Add form control to the sign-up page.
- **Field Validation:** Implement validation to ensure that the submit buttons remain disabled until all required fields have valid input values.

## Objective
The objective of this issue is to assign a contributor to implement form control on the sign-in and sign-up pages, ensuring that users cannot submit the form until they have provided valid input for all required fields. This enhancement will improve the user experience by guiding users to input the necessary information correctly.

## Collaboration
Contributors with experience in frontend development and familiarity with form validation techniques are encouraged to participate in this task. Let's collaborate to enhance the functionality and usability of our sign-in and sign-up pages.

## Feedback
Your feedback or suggestions regarding the implementation of form control on the sign-in and sign-up pages are welcome to ensure that we meet the needs of our users effectively.

Thank you for your attention to this matter, and let's work together to improve our application!

**Comment by CoderSwarup** [comment]
Can u please assign this issue to me , I want to work on this issue

**Comment by Tomkndn** [comment]
I would like to work on this task, can you please assign me this issue.

**Comment by rajat99-default** [comment]
bro I think I have solved this issue
please assign me this and I will open a PR

**Comment by MAVRICK-1** [comment]
if didn't any update from @CoderSwarup by 9:00 pm today, it will be assigned to @Tomkndn  followed by @rajat99-default

**Comment by rajat99-default** [comment]
Compiled with problems:
×
ERROR
[eslint] 
src\pages\SignIn\index.js
  Line 114:87:  'signInWithGoogle' is not defined  no-undef
  Line 115:47:  'GoogleImg' is not defined         no-undef
  Line 120:75:  'forgotPassword' is not defined    no-undef

Search for the keywords to learn more about each error.

**Comment by MAVRICK-1** [comment]
@rajat99-default  those are eslint problems not major one #4 is raised to create an eslint file to remove this issues.

**Comment by sachin0986** [comment]
I have worked on great ReactJs projects, after reviewing this, I think that I have relevant skills and experience, I believe I can make a meaningful contribution. Please assign me for this.

**Comment by kashi-verma** [comment]
I am a  confident full stack web developer , Please assign this issue to me I assure you that I will definately be valueable for this project .
