### ISSUE TITLE
GoToTop Issue

### ISSUE THREAD

**Issue by Hemu21** [MAVRICK-1/e-commerce_website#183]
**Describe the bug**
Go to Top Code existed but there is a bug. It is Not working.

**Expected behavior**
Go to Top Code existed but there is a bug. It is Not working. Should work properly as expected.

**Comment by Hemu21** [comment]
@MAVRICK-1 can  you please assign this to me.

**Comment by MAVRICK-1** [comment]
@Hemu21 go ahead
