### ISSUE TITLE
 Update Twitter Logo to Newer Version

### ISSUE THREAD

**Issue by prachi-kurmi** [MAVRICK-1/e-commerce_website#184]
**Describe the bug**
The current Twitter logo is outdated and needs to be replaced with the newer version.

**To Reproduce**

1. Go to 'website'
2. Scroll down to 'Footer section'
3. Observe the outdated Twitter logo.

**Expected behavior**
The Twitter logo should be updated to the newer version.

**Screenshots**

![Screenshot 2024-05-19 112701](https://github.com/MAVRICK-1/e-commerce_website/assets/125259987/9644fb58-86f8-4954-92ae-0014f0abeafe)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

 @MAVRICK-1 , I would like to work on this task as part of GSSoC'24. I understand it is a small issue, but it is important for maintaining the website's branding. Please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@prachi-kurmi okay go ahead

**Comment by prachi-kurmi** [comment]
@MAVRICK-1  I tried to add Material UI icons, but I encountered an error. I also attempted to run the dependencies, but that didn't work. Instead of Material UI, I used React Icons, but they appear slightly misaligned. Should I replace all the "Follow Us" icons with React Icons or take a different approach?

![Screenshot 2024-05-19 205457](https://github.com/MAVRICK-1/e-commerce_website/assets/125259987/560bb6f7-323f-45e0-be58-38ef8801a136)

**Comment by MAVRICK-1** [comment]
@prachi-kurmi material ui should work , do one thing update your branch take the reference of this PR #187

**Comment by MAVRICK-1** [comment]
@prachi-kurmi just add a twitter button

**Comment by prachi-kurmi** [comment]
@MAVRICK-1 When I try to add the Twitter X icon, it gives an error


![Screenshot 2024-05-20 093122](https://github.com/MAVRICK-1/e-commerce_website/assets/125259987/9dcf8b61-aa7e-41f9-a65e-007eaf0cfc07)


but when I add any other icon, it doesn't give an error


![Screenshot 2024-05-20 092225](https://github.com/MAVRICK-1/e-commerce_website/assets/125259987/1f91f603-5f2f-4ff0-9fc9-9aa8723b40d3)

**Comment by MAVRICK-1** [comment]
@prachi-kurmi X icon is added in v5, it does not exist in v4. Try to update the version

**Comment by MAVRICK-1** [comment]
I will mark it as level2

**Comment by prachi-kurmi** [comment]
okay thank you

**Comment by TheNikhilRaj** [comment]
I would like to work on this issue , please assign this to me.
@MAVRICK-1
