### ISSUE TITLE
forget password page ui design 

### ISSUE THREAD

**Issue by Parimalasri13** [MAVRICK-1/e-commerce_website#186]
when we click on forget option on sign in page it is redirecting to 404 page not found error

**Comment by Parimalasri13** [comment]
@sanjay-kv can you please assign this to me under gssoc'24

**Comment by MAVRICK-1** [comment]
@Parimalasri13 update the branch

**Comment by Parimalasri13** [comment]
@MAVRICK-1 can you please assign and add level , i already created  branch and made pullrequest
