### ISSUE TITLE
Eliminate Repetitive Contact info

### ISSUE THREAD

**Issue by sau-mili** [MAVRICK-1/e-commerce_website#191]
**Describe the bug**
The contact number is shown twice in the footer

**To Reproduce**
I will eliminate one of the two same things, and fix the alignment afterwards

1. Go to 'website'
2. Click on 'nothing.'
3. Scroll down to 'footer"

**Expected behavior**
I expect to see only one contact details, now there are two

**Screenshots**
![Screenshot 2024-05-20 003229](https://github.com/MAVRICK-1/e-commerce_website/assets/146661411/a7f38596-4565-4c95-ad5c-fd21cfad3149)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MAVRICK-1** [comment]
@sau-mili go ahead

**Comment by Vinaysohaliya** [comment]
I would like to work on this issue. Please assign it to me under GSSOC'24.
