### ISSUE TITLE
Changing favicon icon

### ISSUE THREAD

**Issue by kashhisshh** [MAVRICK-1/e-commerce_website#196]
as the current icon is not that visible i will just change crop the name from your logo

**Comment by MAVRICK-1** [comment]
@kashhisshh okay go ahead ,but don't delete the current icon from asset .

**Comment by kashhisshh** [comment]
Okay suree

**Comment by kashhisshh** [comment]
![Screenshot 2024-05-21 005643](https://github.com/MAVRICK-1/e-commerce_website/assets/68736387/277da1f8-0f99-4ccd-a3e3-79bf84142131)
![Screenshot 2024-05-21 005704](https://github.com/MAVRICK-1/e-commerce_website/assets/68736387/64e8d461-740c-4706-a25c-b14cb8476539)

**Comment by kashhisshh** [comment]
which one like you suggest

**Comment by MAVRICK-1** [comment]
@kashhisshh 2nd one

**Comment by kashhisshh** [comment]
Okay then leeme change.... I have asked from friends they said 1st so I maked a pull req from 1st
