### ISSUE TITLE
Improve UI of scroll to top widget

### ISSUE THREAD

**Issue by sau-mili** [MAVRICK-1/e-commerce_website#198]
![Screenshot 2024-05-20 222706](https://github.com/MAVRICK-1/e-commerce_website/assets/146661411/a586376c-14d1-4c0f-b5dc-2de79f9ad193)
The UI of this widget doesn't match the website theme. I wish to improve it and add animations to it.

Please assign me this

**Comment by MAVRICK-1** [comment]
@sau-mili okay go ahead.
