### ISSUE TITLE
Display Success Message and Redirect User After Sign Up

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#2]
### Description
Currently, upon successful [sign-up](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/SignUp), the user is not provided with any indication that their account creation was successful, nor are they redirected to the sign-in page. We need to implement a feature to display a success message in a modal dialog to the user after they successfully sign up. Additionally, upon closing the modal, the user should be redirected to the sign-in page.

### Implementation
We will utilize Material-UI's Dialog component to create a modal dialog for displaying the success message. Upon successful sign-up, we will trigger this modal to appear, informing the user that their account has been created successfully and prompting them to sign in. Upon closing the modal, the user will be redirected to the[ sign-in](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/SignIn) page using React Router's useHistory hook.

### Steps to Implement
1. **Define State for Modal**: Create state variables to manage the visibility of the success modal.
2. **Display Modal**: Implement a modal dialog using Material-UI's Dialog component to display the success message.
3. **Close Modal and Redirect**: Provide options to close the modal and redirect the user to the sign-in page upon clicking the "Sign In" button.
4. **Update Sign-Up Function**: After successful user sign-up, trigger the modal to appear.
5. **Use useHistory for Redirection**: Utilize React Router's useHistory hook to redirect the user to the sign-in page.

### Material-UI Dialog Documentation
You can refer to the Material-UI documentation for more information on how to use the Dialog component:
[Material-UI Dialog Documentation](https://mui.com/components/dialogs/)

### Code Changes
```jsx
// Inside SignUp component
import { Dialog, DialogActions, DialogContent, DialogContentText, DialogTitle } from '@mui/material';
import { useHistory } from 'react-router-dom';

// Define state variables for success modal and useHistory hook
const [showSuccessModal, setShowSuccessModal] = useState(false);
const history = useHistory();

// Function to handle successful sign-up
const handleSignUpSuccess = () => {
    setShowSuccessModal(true); // Trigger success modal
};

// Function to close modal and redirect to sign-in page
const handleCloseModalAndRedirect = () => {
    setShowSuccessModal(false);
    history.push('/signIn'); // Redirect to sign-in page
};

// Inside signUp function after user successfully signs up
.then((userCredential) => {
    setShowLoader(false);
    setFormFields({
        email: '',
        password: '',
        conformPassword: ''
    });
    handleSignUpSuccess(); // Trigger success modal
})

// Implement Modal to display success message and redirect
<Dialog
    open={showSuccessModal}
    onClose={handleCloseModalAndRedirect}
    aria-labelledby="alert-dialog-title"
    aria-describedby="alert-dialog-description"
>
    <DialogTitle id="alert-dialog-title">{"Account Created Successfully!"}</DialogTitle>
    <DialogContent>
        <DialogContentText id="alert-dialog-description">
            Your account has been created successfully. You can now sign in.
        </DialogContentText>
    </DialogContent>
    <DialogActions>
        <Button onClick={handleCloseModalAndRedirect} color="primary" autoFocus>
            Sign In
        </Button>
    </DialogActions>
</Dialog>
```
### 1. Perform a sign-up process with valid credentials.
Ensure you have valid credentials ready for sign-up.

### 2. Verify that upon successful sign-up, a modal dialog appears with the success message.
- Complete the sign-up process with valid credentials.
- After successful sign-up, verify that a modal dialog appears on the screen.
- Confirm that the modal displays the success message indicating that the account has been created successfully.

### 3. Confirm that the modal dialog provides an option to redirect to the sign-in page.
- In the modal dialog, check for an option/button labeled "Sign In".
- Ensure that this option is clearly visible and clickable.

### 4. Clicking on "Sign In" in the modal should redirect the user to the sign-in page.
- Click on the "Sign In" button within the modal dialog.
- Verify that upon clicking, the modal closes, and the user is redirected to the sign-in page.

### 5. Ensure the modal does not appear if sign-up fails or if the user closes it manually.
- Attempt to sign up with invalid credentials or by leaving required fields blank.
- Verify that the modal does not appear upon failed sign-up attempts.
- Manually close the modal if it appears after successful sign-up and confirm that it does not reappear.

**Comment by Mr-mahato** [comment]
I'm interested in working on the open issue regarding the Display Success Message and Redirect User After Sign Up. I have experience with Node.js, Express, MongoDB,Material-UI , tailwind  and JWT token handling, which aligns well with the project's requirements.

I've reviewed the issue's description and requirements and feel confident that I can deliver a robust and secure  solution. I understand the need for proper flow of program and am ready to address those aspects.

Would you be open to assigning this issue to me? I'm eager to contribute to the project and believe I have the skills necessary to complete this task within the estimated timeframe.

**Comment by MAVRICK-1** [comment]
@Mr-mahato The coding period will start from 7 pm , First come first serve basis it will assign to you , we are using firebase as backend, If you need any help on that let me know

**Comment by Mr-mahato** [comment]
I have worked with express , jwt , mongodb for backend . I know that i have not used firebase for the backend very often . But i guess learning by doing in solving this issue will be one challenge for me which i will loved, so to get proper understanding of the firebase working and expanding my horizon of knowledge  seeking help in the community , i am kindly seeking a chance to work on this issue.

**Comment by Mr-mahato** [comment]
Hi @MAVRICK-1  I found that useHistory() hook was deprecated  , i am using useNavigate() for the navigation from the signup page to the signin page.

**Comment by priyankMS** [comment]
hi @MAVRICK-1  one create private route and and set then component when user was login is auth is true and private compament outlat was show, other wise rediect login page

**Comment by MAVRICK-1** [comment]
@Mr-mahato any updates ? or should i assign this to @priyankMS ?

**Comment by Mr-mahato** [comment]
I am working on it. It will be done soon.

**Comment by Mr-mahato** [comment]
@MAVRICK-1  i have done the code but there is small issue that i have encounter ,
when i am trying to merge the main branch with my branch using 
git pull origin main 
![Screenshot from 2024-05-12 22-34-39](https://github.com/MAVRICK-1/e-commerce_website/assets/96912116/29ca2d1a-cd3a-41bf-b16b-dd154c23cb96)
i am facing this error how to solve this?

**Comment by MAVRICK-1** [comment]
@Mr-mahato you are getting merge conflict [video](https://www.youtube.com/watch?v=xNVM5UxlFSA) checkout this video it will help you to understand it . Take your time

**Comment by Mr-mahato** [comment]
I have creaed a PR you can review it.
