### ISSUE TITLE
Send Email Responsvive Bug

### ISSUE THREAD

**Issue by vivekop0** [MAVRICK-1/e-commerce_website#20]
when you switch to mobile the send email is not shown proper 

**To Reproduce**

**Expected behavior**
this shold be resonsive as per the bottom send email box 

**Screenshots**
![Screenshot (54)](https://github.com/MAVRICK-1/e-commerce_website/assets/118190749/5e9071e1-a72a-4ba1-9f2e-a67d0e7f8aa3)

**Desktop (please complete the following information):**

- OS: [Window 11 ]
- Browser [ chrome]
- Version [ 124.0.6367.201 ]

**Smartphone (please complete the following information):**

- Device: [Realme 8]
- OS: [ Android]
- Browser [crome]
- Version [124.0.6367.201 ]

**Additional context**

**Comment by vivekop0** [comment]
please Assign Me this under GSSOC '24

**Comment by MAVRICK-1** [comment]
https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/5c073bf6-aed9-40de-9d82-263dfe882e01

Hey @vivekop0 , everything seems to be working smoothly. Please try refreshing the page and granting access to your location. Our application requires location access to sort nearby products effectively.

**Comment by vivekop0** [comment]
ok sir
