### ISSUE TITLE
OTP verification system for sign in and login functionality

### ISSUE THREAD

**Issue by mr0nerd** [MAVRICK-1/e-commerce_website#203]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I think about the security of user accounts on our platform. Currently, our sign-in and login processes rely solely on passwords, which can be vulnerable to various attacks such as brute force or phishing. Without an additional layer of security, user accounts are at a higher risk of unauthorized access.

**Describe the solution you'd like**
I would like to see the implementation of OTP (One-Time Password) verification as part of the sign-in process. This would work by sending an OTP to the user's registered email address after they enter their username and password. The user would then need to enter the OTP to complete the sign-in process, thereby adding an extra layer of security.

**Describe alternatives you've considered**

- **Security Questions**: Asking users to answer pre-set security questions as an additional verification step. However, this method can be less secure if the answers are easily guessable or obtainable.

**Additional context**
Implementing OTP verification will significantly enhance the security of user accounts by ensuring that only users with access to their email can log in. This is especially crucial for applications handling sensitive information, such as financial services, like in a ecommerce site

Several other platforms have successfully implemented OTP verification to enhance security, including major banks and social media services and E-commerce platforms. This feature can also help in complying with regulatory requirements for user data protection.

**Comment by MAVRICK-1** [comment]
@mr0nerd how will you do that ?

**Comment by MAVRICK-1** [comment]
@mr0nerd okay go ahead

**Comment by MAVRICK-1** [comment]
@mr0nerd include the button below , the sign in with  google button

**Comment by MAVRICK-1** [comment]
> which solution should i implement ? solution 1 0r 2 @MAVRICK-1

solution 1

**Comment by mr0nerd** [comment]
Ok

**Comment by mr0nerd** [comment]
@MAVRICK-1 to implement phone verification via firebase you need to add phone number as a new sign-in method in authentication tab in your firebase project console and enable it, or you can give access of your firebase project console to me.

-Go to the Firebase Console.
-Select your project.
-Navigate to the Authentication section from the left-hand menu.
-Click on the Sign-in method tab.
-Enable Phone under Sign-in providers.

so please help me out here

**Comment by MAVRICK-1** [comment]
@mr0nerd done , but  SMS daily quota of 10/day. so do some error handling if the quota expired

**Comment by mr0nerd** [comment]
Alright

**Comment by mr0nerd** [comment]
@MAVRICK-1 The feature has been built. 


![Screenshot 2024-05-26 144456](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/e498042c-4373-497a-b2c4-0ca9f5e90063)

![Screenshot 2024-05-26 144542](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/d3e9abd6-5bcb-4133-8ceb-b336c9984261)

After Sign up user will be asked to verify his/her phone number and will be taken to phone number otp verification page

![Screenshot 2024-05-26 144609](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/3952567a-ae99-4240-a85f-9861e2fa3003)

![Screenshot 2024-05-26 144727](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/b355e5d5-e4d5-4218-bc97-63b424f80686)

User will verify his/her phone number via Otp

![Screenshot 2024-05-26 144749](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/24020a28-0b84-4ca7-965c-a508baa96814)

After successful verification user will be taken to Sign in page

**Comment by mr0nerd** [comment]
Also if 10 SMS is already sent in a day then it redirects you to the SignIn page

**Comment by mr0nerd** [comment]
@MAVRICK-1 The earlier version started making some errors so I have made some changes in the solution.



![Screenshot 2024-05-27 191129](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/9b140bb5-895d-4a06-8148-f54260590816)

Now the phone verification process will happen in SignUp page only 

![Screenshot 2024-05-27 191230](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/10b6983e-0f28-4c03-93d0-5a997238fd5a)


![Screenshot 2024-05-27 191436](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/ea50f819-b49a-4b88-9b9a-53c70b487c6a)

Only when user has verified his/her phone number then he/she will be directed to the SignIn page

![Screenshot 2024-05-27 212819](https://github.com/MAVRICK-1/e-commerce_website/assets/148885897/8d63f9aa-122f-4c7e-bf4c-4c899866bb19)

If 10 sms has already been sent in a day for Otp verification then Phone Otp verification field will be removed

**Comment by MAVRICK-1** [comment]
@mr0nerd raise a pr

**Comment by mr0nerd** [comment]
It was nice contributing this repo
