### ISSUE TITLE
Cart notification 

### ISSUE THREAD

**Issue by vivekop0** [MAVRICK-1/e-commerce_website#21]
**Describe the bug**
when you added a item to card item added but card notification not increase it not mark as something added

**To Reproduce**

1. Go to ' item'
2. Click on 'add.'
3. Scroll up to 'cart'

**Expected behavior**
after adding item it notification cout should be increase

**Screenshots**
![Screenshot (56)](https://github.com/MAVRICK-1/e-commerce_website/assets/118190749/1303538d-b5a9-4f5e-994a-1646ddf7e771)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MAVRICK-1** [comment]
@vivekop0  
Okay  go ahead!
