### ISSUE TITLE
Add more content to About Page

### ISSUE THREAD

**Issue by sau-mili** [MAVRICK-1/e-commerce_website#210]
Kindly assign me this, so that I can work on this

**Comment by MAVRICK-1** [comment]
@sau-mili what type of content

**Comment by Divi-1026** [comment]
Can you please assign this issue to me as I created so many about pages so i will add more content ..!!

**Comment by MAVRICK-1** [comment]
@sau-mili what more you wanna add ?

**Comment by MAVRICK-1** [comment]
@Divi-1026  what you wanna add ?

**Comment by sau-mili** [comment]
The about page currently has only contributors list.
I was thinking, we could add description of the page first then the list of contributors

**Comment by sau-mili** [comment]
@MAVRICK-1 It was my issue :(

**Comment by MAVRICK-1** [comment]
@sau-mili i haven't got any reply from you for that, I assigned her

**Comment by sau-mili** [comment]
It's okay, I will raise another issue.. But please wait for me.. I have exams ongoing, so I might take some time to reply, but I surely will

**Comment by MAVRICK-1** [comment]
No issues, mine exam is also going on . Atleast inform that before hand in
your issue. Then it will easy for me . 👍🙂.

**Comment by MAVRICK-1** [comment]
@sau-mili I am assigning this issue to you then .

**Comment by sau-mili** [comment]
okay, thanks
