### ISSUE TITLE
Auto Commenting when a PR is merged

### ISSUE THREAD

**Issue by suhanipaliwal** [MAVRICK-1/e-commerce_website#211]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by MAVRICK-1** [comment]
@suhanipaliwal can you provide any example or documentation about this ?

**Comment by suhanipaliwal** [comment]
A comment like this will be made as soon as a pull request is merged
<img width="800" alt="Screenshot 2024-05-25 at 12 28 52 PM" src="https://github.com/MAVRICK-1/e-commerce_website/assets/161575955/4a172702-b6be-4ed7-b305-45ab5ef893cc">

**Comment by MAVRICK-1** [comment]
@suhanipaliwal it's not needed
