### ISSUE TITLE
Update the react-router-dom to the latest version v6.4 making it more convenient for the developers 

### ISSUE THREAD

**Issue by MinavKaria** [MAVRICK-1/e-commerce_website#213]
**Is your feature request related to a problem? Please describe.**
The current routing setup is cumbersome and difficult to manage due to the older version of React Router DOM.

**Describe the solution you'd like**
Update React Router DOM to v6, using createBrowserRouter and RouterProvider for a more efficient routing setup. This will simplify nested routes and improve code maintainability.

**Describe alternatives you've considered**
- Continuing with the older version, which is not sustainable due to deprecated features.
- Using a different routing library, requiring a significant rewrite.

_GSSOC'2024 Contribuitor_

@MAVRICK-1  Please assign this to me

**Comment by MAVRICK-1** [comment]
@MinavKaria okay go ahead , i will give you level after seeing your pr

**Comment by MinavKaria** [comment]
> @MinavKaria okay go ahead , i will give you level after seeing your pr

I have sent the PR please check let me know

**Comment by MinavKaria** [comment]
And also tag Firebase is not appropriate for it , please add the level to it too
