### ISSUE TITLE
[NEW FEATURE] Adding A Modal Component To Display Deal of the Day

### ISSUE THREAD

**Issue by shubhanshukaintura** [MAVRICK-1/e-commerce_website#214]
**Is your feature request related to a problem? Please describe.**
Integrate a modal component to highlight the daily deal, enhancing user engagement and visibility of time-sensitive offers. The addition of a modal component will elevate user experience and maximize the promotional potential of daily deals.

**Describe the solution you'd like**
Implement a modal component that is triggered to display the "Deal of the Day" each time a user visits the site. Upon landing on the platform, the modal should automatically appear, prominently showcasing the current daily deal. The modal should feature visually appealing design elements and concise messaging to effectively communicate the details of the offer. Additionally, provide options for users to easily dismiss the modal or take action to avail themselves of the deal directly from within the modal interface.

**Describe alternatives you've considered**
Email Subscription: Encourage users to subscribe to email notifications specifically for receiving updates about the daily deal. By collecting email addresses and sending targeted emails with details of the deal, users can stay informed about the offer even when not actively browsing the site.

**Additional context**
The addition of a modal component to display the "Deal of the Day" represents a strategic enhancement aimed at improving user engagement, increasing visibility of time-sensitive offers, and ultimately driving conversion rates. This feature aligns with the platform's objective of delivering an intuitive and rewarding user experience while maximizing the promotional potential of daily deals.

**Comment by shubhanshukaintura** [comment]
Please Assign me this issue under GSSOC 2024. I would like to work on it.

**Comment by MAVRICK-1** [comment]
@shubhanshukaintura okay go ahead , select the best deal of the randomly from the given product
