### ISSUE TITLE
"Enhancing the wishlist Page"

### ISSUE THREAD

**Issue by shreya1510ss** [MAVRICK-1/e-commerce_website#215]
Is your feature request related to a problem? Please describe.
The presence of the "Proceed to checkout" box on the wishlist page creates confusion and disrupts the user experience. Users often find it misleading, as they are typically not ready to proceed to checkout when viewing their wishlist items.
I would also like to implement a confirmation message or toast notification to inform users when an item has been successfully moved to the cart.

Describe the solution you'd like
I propose removing the "Proceed to checkout" box from the wishlist page and replacing it with a "Move to cart" button for each item in the wishlist. This change will streamline the user experience, allowing users to easily transfer items from their wishlist to their shopping cart.

![gssoc2](https://github.com/MAVRICK-1/e-commerce_website/assets/84861803/930d8fc6-7ef9-4480-aa2a-f8294f445045)

 @MAVRICK-1 please assign me this issue i want to work on this issue

also if their any design available in your mind then please also provide me that

**Comment by MAVRICK-1** [comment]
@shreya1510ss great idea , you need access of firebase to move the items to cart . send me your email . also look for duplicate element.

**Comment by shreya1510ss** [comment]
@MAVRICK-1 email: shreyasharma.1510001@gmail.com.

**Comment by MAVRICK-1** [comment]
@shreya1510ss check your email , and also follow the path

**Comment by shreya1510ss** [comment]
@MAVRICK-1  is this UI for wishlist page ok for you?
![gssoc4](https://github.com/MAVRICK-1/e-commerce_website/assets/84861803/949b586c-d7b9-4e0a-876b-60d0e0e3899b)

**Comment by shreya1510ss** [comment]
I was thinking that whenever the user clicks on "move to cart" button, the product gets added in the cart and gets removed from the wishlist. What do you think about this?

**Comment by MAVRICK-1** [comment]
@shreya1510 fix the image of the items and move the product to the cart and check the product is already there or not . Then delete the product from wishlist.
