### ISSUE TITLE
Alignment of  the featured categories 

### ISSUE THREAD

**Issue by shrutigolwalk0109** [MAVRICK-1/e-commerce_website#220]
If we align the features categories section to the center and also maintain its width and position so it looks good .

Kindly Assign me this issue under GSSOC'24.

Screenshot:

Before :

![WhatsApp Image 2024-05-23 at 19 51 20_1f927af8](https://github.com/MAVRICK-1/e-commerce_website/assets/132553685/14abce5a-cc4b-4362-87d8-34cc6de3073f)

After fixing:

![WhatsApp Image 2024-05-23 at 19 49 43_00b87077](https://github.com/MAVRICK-1/e-commerce_website/assets/132553685/609c32f3-9af6-48a2-8952-8b5d757e3475)

**Comment by MAVRICK-1** [comment]
@shrutigolwalk0109 thanks for the suggestion but i like the current design
