### ISSUE TITLE
Email and Number is not redirecting.

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [MAVRICK-1/e-commerce_website#228]
**Describe the bug**
It should work and redirect us directly on mail and dial pad.

**To Reproduce**

1. Go to 'Home Page - Footer'
2. Click on 'email and number'
4. See bug

**Screenshots**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/121503426/bb605084-d982-4e4d-bd55-ff8712082967)

- OS: [e.g. Linux]
- Browser [e.g. chrome]

**Comment by MAVRICK-1** [comment]
@SyedImtiyaz-1 closed by #202
