### ISSUE TITLE
Add "Privacy policy" and "Terms and Conditions" Pages to Website 

### ISSUE THREAD

**Issue by MastanSayyad** [MAVRICK-1/e-commerce_website#229]
Hey @MAVRICK-1  I would like to add dedicated pages for "Privacy Policy" and "Terms and Conditions"

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/6bf9d1b7-bc48-4f11-9d63-3f054d644d9b)

- For example like this:

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/3c37b497-d0c4-4555-a45a-5677978566eb)

Could you please assogn this issue to me under GSSoC'24??

**Comment by MAVRICK-1** [comment]
@MastanSayyad okay go-ahead

**Comment by MastanSayyad** [comment]
Hey @MAVRICK-1 I have made the changes and created the pages but I'm unable to commit. It showing me this error:

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/af7c7ff4-13ac-4d95-85f9-6682fead7a9f)

Can you please let me know what went wrong??
