### ISSUE TITLE
[BUG] : email and subscribe button is not responsive

### ISSUE THREAD

**Issue by Sudhanshu2306** [MAVRICK-1/e-commerce_website#230]
**Describe the bug**
on squeezing the screen size to any size less than 780px, "enter your email" and "subscribe button is not responsive

**To Reproduce**

1. Go to 'https://nestondc.vercel.app/'
2. Click on '.minimize button'
3. See error

**Expected behavior**
it should fit and align properly wrt to the screen size

**Screenshots**
![Screenshot 2024-05-25 110808](https://github.com/MAVRICK-1/e-commerce_website/assets/126086429/c2ad8cf6-0aad-410b-b303-ce62f89ed888)

**Desktop (please complete the following information):**

- OS: [Windows]
- Browser [chrome]

**Comment by Sudhanshu2306** [comment]
@MAVRICK-1 Please assign me this issue!

**Comment by MAVRICK-1** [comment]
@Sudhanshu2306 refresh it .
