### ISSUE TITLE
Bug:  Subscribe Button is not responsive.

### ISSUE THREAD

**Issue by Dishika18** [MAVRICK-1/e-commerce_website#231]
**Describe the bug**
The Subscribe button is not responsive and is overflowing from the screen.

**Expected behavior**
I can Fix this and make it responsive. Please assign me this issue under GSSoC'24. 

**Screenshots**
![Screenshot 2024-05-25 135257](https://github.com/MAVRICK-1/e-commerce_website/assets/152963337/ef22a564-2dc0-4f0a-bdb1-545f0142ec06)

**Comment by MAVRICK-1** [comment]
@Dishika18 refresh it ,
