### ISSUE TITLE
Improving the user experience by adding a loading state, and improving performance by updating the local state instead of re-fetching the entire cart.

### ISSUE THREAD

**Issue by SamFusedBits** [MAVRICK-1/e-commerce_website#233]
**Is your feature request related to a problem? Please describe.**
 Yes, the feature request is related to two problems. First, when fetching cart products, there's no loading state, which can lead to a poor user experience if the fetch operation takes a long time. Second, the deleteCartItem and deleteAllCartItems functions both delete items and then re-fetch the entire cart, which could be a performance issue if the cart has a lot of items.

**Describe the solution you'd like**
I would like two solutions to be implemented. First, add a loading state that's displayed while the fetch operation is in progress. This can be done by using a useState hook to manage the loading state. Second, instead of re-fetching the entire cart, update the local state to reflect the changes. This can be done by filtering out the deleted item from the cartItems state in the deleteCartItem function, and setting cartItems to an empty array in the deleteAllCartItems function.

**Additional context**
The current implementation can lead to a poor user experience and potential performance issues, especially when the cart has a lot of items. By implementing these solutions, we can improve the user experience and the performance of the application.

**Comment by MAVRICK-1** [comment]
@SamFusedBits okay go ahead, I will mark the level after seeing your PR
