### ISSUE TITLE
home page is not responsove

### ISSUE THREAD

**Issue by AMISH-KHAN** [MAVRICK-1/e-commerce_website#234]
**Describe the bug**

there is very little responsiveness at home page

https://github.com/MAVRICK-1/e-commerce_website/assets/123164129/6a39772e-6617-4fc9-a4a3-128d971d8edd

**Additional context**
Please assign this issue to me under gssoc

**Comment by MAVRICK-1** [comment]
Refresh it

**Comment by MAVRICK-1** [comment]
@AMISH-KHAN it's totally responsive
