### ISSUE TITLE
newsLetterBanner div can be made responsive for varying dimension

### ISSUE THREAD

**Issue by shivam2027** [MAVRICK-1/e-commerce_website#238]
**Describe the bug**
newsLetterBanner div  go out of the container-fluid at certain dimensions.

**Expected behavior**
newsLetterBanner div should fit container-fluid div with all varying dimensions.

**Screenshots**
![Screenshot 2024-05-26 154310](https://github.com/MAVRICK-1/e-commerce_website/assets/152594323/3da0cba2-1c1f-4b84-b0be-3a8e4eb65987)

**Additional context**
@MAVRICK-1 please assign me this issue i want to work on this issue

also if their any design available in your mind then please also provide me that

**Comment by MAVRICK-1** [comment]
@shivam2027 okay go ahead
