### ISSUE TITLE
Profile Image Not Displaying Upon Sign-in

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#24]
## Issue Title
Profile Image Not Displaying Upon Sign-in

<img width="89" alt="Screenshot 2024-05-09 223848" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/c54f87f4-ebef-4d29-9089-477dc6ff6aff">

### Issue Description
Upon signing in, users are encountering an issue where their profile image fails to display correctly. Currently, the profile image is not showing up for users who sign in using their email and password. However, users signing in via Google authentication are able to see their Google profile image as expected.

### Expected Behavior
- When a user signs in using their email and password, their profile image should be displayed.
- When a user signs in using Google authentication, their Google profile image should be displayed.

### Steps to Reproduce
1. Navigate to the sign-in page.
2. Enter valid credentials (email and password) and sign in.
3. Observe that the profile image is not displayed.

### Proposed Solution
- For users signing in using email and password authentication, display a default [SVG image](https://icons8.com/icon/HmQQr0jYHZxu/male-user).
![icons8-user](https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/6b30839f-05a3-4e2a-a4ba-5c28935d81da)

- For users signing in via Google authentication, retrieve and display their Google profile image.

### Priority
High

### Labels
bug, enhancement, authentication

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this to me

**Comment by MAVRICK-1** [comment]
@Hemu21 go ahead

**Comment by Hemu21** [comment]
@MAVRICK-1  can you please check this demo pictures. If it is ok then I will create the PR.

### With mail
![withmail](https://github.com/MAVRICK-1/e-commerce_website/assets/106808387/3321ae42-b2a2-4e7c-9899-ae2899a2a0dd)

### with google
![withgoogle](https://github.com/MAVRICK-1/e-commerce_website/assets/106808387/60c2e95c-9097-4a05-acc6-0a9f566d85d7)

**Comment by MAVRICK-1** [comment]
remove the account word and make it slightly bigger , and check it's responsive or not

**Comment by Hemu21** [comment]
ok

**Comment by Hemu21** [comment]
@MAVRICK-1 I had created the PR. Can you please Check it.
