### ISSUE TITLE
Link issue in footer

### ISSUE THREAD

**Issue by SakiraAli1115** [MAVRICK-1/e-commerce_website#240]
Hello PA,

Link issue in footer
Please assign me this issue!

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/169131830/8028fbfb-ed18-41f7-a0d0-900de0b4172b)

**Comment by MAVRICK-1** [comment]
@SakiraAli1115 it is already solved, you are seeing deployment of main branch, the current update branch is dev branch.
