### ISSUE TITLE
Adding search bar 

### ISSUE THREAD

**Issue by SakiraAli1115** [MAVRICK-1/e-commerce_website#241]
Hello PA,

Adding js to unable search bar!

Please assign me this issue! 

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/169131830/d93f4c44-fe02-4d54-9139-18a475490980)

**Comment by SyedImtiyaz-1** [comment]
She is adding Search Bar.
Assign this to @SakiraAli1115 👍🏻

**Comment by MAVRICK-1** [comment]
@SyedImtiyaz-1 it's already done in dev branch , but haven't merge in main branch
