### ISSUE TITLE
Adding a go to top button feature

### ISSUE THREAD

**Issue by suhanigupta23** [MAVRICK-1/e-commerce_website#245]
We can add a go to top by clicking on a button 
<img width="725" alt="Screenshot 2024-05-26 at 6 05 11 PM" src="https://github.com/MAVRICK-1/e-commerce_website/assets/144280247/af9d442a-dca0-4231-9147-b1780b746deb">

I want to work on this under Gssoc'24.

**Comment by MAVRICK-1** [comment]
@suhanigupta23 already it's been added
