### ISSUE TITLE
About Us section should be designed properly to  highlight features of Nest

### ISSUE THREAD

**Issue by Vin205** [MAVRICK-1/e-commerce_website#252]
**Is your feature request related to a problem**
The about us section doesn't specify the information about Nest at the end of About US page and this information should be displayed at the top to know more about Nest

**Describe the solution you'd like**
The about section section should include the features of Nest and what Nest is all about. 

**Describe alternatives you've considered**
About us section will contain information about what is Nest. 
It will features such as exclusive products with exclusive offers
Assured discounts and delivery services. Along with some images so the UI looks appealing to Users

**Additional context**
![IMG_20240528_193842](https://github.com/MAVRICK-1/e-commerce_website/assets/138381350/3dd85187-5dfd-4eb8-b820-d16958bca409)
![IMG_20240528_193859](https://github.com/MAVRICK-1/e-commerce_website/assets/138381350/fdb7a5a0-3714-4393-86b7-5ca368855877)

**Comment by MAVRICK-1** [comment]
closed by #253
