### ISSUE TITLE
navbar is not aligned properly.

### ISSUE THREAD

**Issue by prachita0504** [MAVRICK-1/e-commerce_website#254]
**Is your feature request related to a problem? Please describe.**
Navbar is aligned by which it's not look good 
**Describe the solution you'd like**
We can improve it by change the CSS.
![Screenshot 2024-05-28 203422](https://github.com/MAVRICK-1/e-commerce_website/assets/139040702/bab6068a-6c0b-43d5-8c74-2ea1990c74f2)

**Comment by MAVRICK-1** [comment]
closed by #251
