### ISSUE TITLE
Separate page for contributors & About us Optimize

### ISSUE THREAD

**Issue by Hemu21** [MAVRICK-1/e-commerce_website#257]
**Is your feature request related to a problem? Please describe.**
As it is a open source project. It is important to show the contributors.

**Describe the solution you'd like**
Make separate page for contributors.

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this to me.

**Comment by MAVRICK-1** [comment]
@Hemu21 okay go ahead
