### ISSUE TITLE
Nav bar items overflow

### ISSUE THREAD

**Issue by Hemu21** [MAVRICK-1/e-commerce_website#259]
**Describe the bug**
Currently navbar items are getting overflow. 

**Expected behavior**
Nav bar items should align properly in single row.

**Comment by Hemu21** [comment]
@MAVRICK-1  can you please assign this to me

**Comment by sanket95droid** [comment]
@Hemu21 Can you provide screenshots or any kind of validation? I'll assign it to you

**Comment by Hemu21** [comment]
At laptop screen  1024px nav bar items are overflows 
![20240529_213207](https://github.com/MAVRICK-1/e-commerce_website/assets/106808387/3043c26d-b0ad-4064-ab08-0716d6648ecd)

**Comment by Hemu21** [comment]
![20240529_213207](https://github.com/MAVRICK-1/e-commerce_website/assets/106808387/8fa860bd-ea6e-4ec0-b777-b63f4c5acf13)

**Comment by sanket95droid** [comment]
@Hemu21 go ahead!!
