### ISSUE TITLE
404 not found page responsive

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [MAVRICK-1/e-commerce_website#266]
**Is your feature request related to a problem? Please describe.**
Add a 404 not found page for your website

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Hemu21** [comment]
@RamakrushnaBiswal  404 page is existed, but the bug is in its redirecting or route. I hope you got it. Update this issue.

**Comment by RamakrushnaBiswal** [comment]
Yh its correct 💯. thanks @Hemu21 🙌

**Comment by sanket95droid** [comment]
@RamakrushnaBiswal can you provide more description of the issue, i'll assign it to you

**Comment by RamakrushnaBiswal** [comment]
@MAVRICK-1 look at the url .i enter a invalid URL but it redirect to to the home page?
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/125277258/b3d95bff-fb75-4c1b-ab7c-37f71f378554)
@sanket95droid

**Comment by MAVRICK-1** [comment]
that's the main branch

**Comment by MAVRICK-1** [comment]
@sanket95droid check the dev branch

**Comment by RamakrushnaBiswal** [comment]
@MAVRICK-1 The deploy default is the main branch,i have no idea about another branch is there sorry for the convince,
can you assign it to me make it responsive

**Comment by RamakrushnaBiswal** [comment]
@MAVRICK-1 Anybody working on the home page responsive ??

**Comment by sanket95droid** [comment]
@RamakrushnaBiswal No not yet!!

**Comment by RamakrushnaBiswal** [comment]
@sanket95droid I do only error page responsive after 3 days i can do the whole page responsive,
Because i have some internship projects need to complete.
can you make it label 2 ?? other projects give the responsive part to label 2.

**Comment by sanket95droid** [comment]
@RamakrushnaBiswal Ok go ahead do it, just change the issue name and description or close and make a new issue?

**Comment by RamakrushnaBiswal** [comment]
@sanket95droid Thank you
