### ISSUE TITLE
[Feature Request]: Enhance User Interaction with Toast Notifications

### ISSUE THREAD

**Issue by mr0nerd** [MAVRICK-1/e-commerce_website#268]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to propose the addition of a toast notification system to the e-commerce site. Toast notifications are small, non-blocking messages that appear temporarily to inform users of actions or events. They are typically used to provide feedback after a user has performed an action, enhancing the overall user experience by providing immediate, contextual information.

### Use Case

Implementing a toast notification system would significantly enhance the user experience by providing real-time feedback for key actions. This would make the site more interactive and user-friendly, improving user satisfaction and engagement.

Specific Use Case
**Scenario:** A user logs in to their account.

**Current State:** The user logs in and is taken to their account dashboard without any confirmation message.
**With Toast Notification:** After logging in, a toast notification appears saying, "Login successful! Welcome back, [User Name]." This enhances the user experience by confirming the action and personalizing the message.
**Scenario:** A user logs out of their account.

**Current State:** The user logs out and is redirected to the homepage without any confirmation.
**With Toast Notification:** Upon logging out, a toast notification appears saying, "You have successfully logged out. See you next time!" This provides closure to the user’s session.
**Scenario:** A user adds an item to their cart.

**Current State:** The item is added to the cart, but there is no immediate visual confirmation other than the cart icon update.
**With Toast Notification:** When the user adds an item to the cart, a toast notification appears saying, "Item added to cart!" This immediate feedback confirms the action without requiring the user to check the cart.
**Scenario:** A user places an order.

**Current State:** The user completes the checkout process and is redirected to the order confirmation page.
With Toast Notification: After placing an order, a toast notification appears saying, "Order placed successfully! Thank you for shopping with us." This adds a final touch of reassurance and appreciation.

### Benefits

1.Improved User Experience: Immediate feedback through toast notifications enhances the user experience by making interactions smoother and more intuitive.
2.Increased User Engagement: Real-time notifications keep users informed and engaged, encouraging them to interact more with the site.
3.Reduced User Uncertainty: Clear and immediate feedback reduces uncertainty and frustration, leading to higher user satisfaction.
4.Professional Touch: Adding toast notifications gives the site a more polished and professional feel, aligning with modern web application standards.
Implementing a toast notification system would provide significant improvements to the user interface and overall experience on the e-commerce site.

### Priority

High

### Record

- [x] I have starred the repository
- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor

**Comment by Tarungupta18** [comment]
@MAVRICK-1  
please assign me

**Comment by mr0nerd** [comment]
I am already working on it please assign me @sanket95droid
