### ISSUE TITLE
[Bug]: The Daily best deals Needs better Orientation in Page 

### ISSUE THREAD

**Issue by Sypher0Dronzer** [MAVRICK-1/e-commerce_website#269]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wish to make this section take up sufficient place within the viewport to make it look better for responsive screens

Please assign this issue to me @MAVRICK-1 

### Expected behavior

The daily best deal should take up the space given and use it efficiently 

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/83546205/60fb3565-88e3-47bf-82bc-17ceb1ce8566)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Sypher0Dronzer ok
