### ISSUE TITLE
[Feature Request]:  Contact Us page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [MAVRICK-1/e-commerce_website#270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I will create a Contact us page for the website .

### Use Case

It will help users to contact for any support .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Ayushmaanagarwal1211 If you can provide a wireframe or sample UI then it would be great !!

**Comment by Ayushmaanagarwal1211** [comment]
Ya Sure and i will email js for integrating mailing facility so is it okay or i need to do this with something else

**Comment by sanket95droid** [comment]
@Ayushmaanagarwal1211 yea great make a PR !!

**Comment by Ayushmaanagarwal1211** [comment]
Ok i am working on that
