### ISSUE TITLE
[Feature Request]: Create careers page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [MAVRICK-1/e-commerce_website#273]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to create a comprehensive and engaging careers page for this e-commerce website. This page will serve as a portal for potential candidates to learn about the company culture, values, current job openings, and the application process.

It will contain below sections,
1. Introduction Section:  welcoming message for potential candidates.

2. Company Overview Section & Why Work with Us Section

3. Current Job Openings Section

4. How to Apply Section

5. Testimonials Section

### Use Case

The aim is to attract talented individuals to join the team.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/139672976/7e6d4435-b365-4859-a6d6-96abe7f382be)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@DharshiBalasubramaniyam thankyou for your suggestion but it's not needed.
