### ISSUE TITLE
[Feature Request]: Create blog page

### ISSUE THREAD

**Issue by DharshiBalasubramaniyam** [MAVRICK-1/e-commerce_website#275]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I would like to create an engaging and informative blog page for this e-commerce website.  It will include sections for featured posts, recent posts, and categories based posts etc.

### Use Case

The blog will serve as a platform to share news, updates, product information, customer stories, and other relevant content to engage with our customers.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@DharshiBalasubramaniyam okay go ahead

**Comment by MAVRICK-1** [comment]
@DharshiBalasubramaniyam will assign you PR after seeing your project
