### ISSUE TITLE
[Feature Request]: Styling in Footer Section

### ISSUE THREAD

**Issue by Damini2004** [MAVRICK-1/e-commerce_website#279]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The requested feature involves improving the styling and functionality of the footer section on a website. This includes ensuring responsive design, optimizing the layout for different screen sizes, and enhancing the visual appeal and usability of the footer, particularly focusing on social media icons.

### Use Case

The enhanced footer section styling focuses on improving the layout, responsiveness, and visual appeal of the footer area on a website. This use case involves the specific enhancements made to the footer section, particularly the resizing and re-arrangement of social media icons and other footer elements.

### Benefits

The enhanced footer section styling will bring numerous benefits to the project, including improved user experience, increased accessibility, better user engagement, and a more professional appearance. By implementing these changes, the project will offer a more polished and user-friendly interface, ultimately contributing to its success and user satisfaction.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@Damini2004 okay go ahead
