### ISSUE TITLE
[Feature Request]: Active current page NavItem button of Navbar

### ISSUE THREAD

**Issue by SrinivasDevolper** [MAVRICK-1/e-commerce_website#280]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

when the user clicks the current page then nav item should be show active on this current pagethe 

### Use Case

User better understanding which navItem clicked.understandunderstand

### Benefits

it is a friendly experience and understanding

### Add ScreenShots

https://github.com/MAVRICK-1/e-commerce_website/assets/121508628/c30dd4be-ee95-4c1d-9d12-dfed5093468a

**I am GSSOC24 Contributor
please assign me, I would like to work on it**

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@SrinivasDevolper okay go Ahead
