### ISSUE TITLE
[Feature Request]: Add FAQ Section to your website

### ISSUE THREAD

**Issue by bhumika-1127** [MAVRICK-1/e-commerce_website#283]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

 I would like to do this task. @MAVRICK-1 @sanket95droid  assign me this task.

### Use Case

Many ecommerce website has FAQ section for better user experience.

### Add ScreenShots

something like this:

![Screenshot 2024-06-01 015755](https://github.com/MAVRICK-1/e-commerce_website/assets/137604220/ef4bd684-1a34-449d-8b03-5ac4602d905c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@bhumika-1127 okay go ahead, Css class must be hierarchical

**Comment by MAVRICK-1** [comment]
@bhumika-1127 will assign level after seeing your pr
