### ISSUE TITLE
[Feature Request]: Add "Back to Top" Button on Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [MAVRICK-1/e-commerce_website#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The addition of a "Back to Top" button on the homepage of our website would enhance user experience by providing a convenient way for users to quickly return to the top of the page after scrolling down. This feature is commonly seen on many websites and has become an expected element for smooth navigation.

### Use Case

- Convenience: Quickly returns users to the top of the page with one click.
- Improved Navigation: Simplifies moving back to the main navigation menu or introductory content.
- Accessibility: Helps users with mobility issues or those using keyboard navigation.
- Enhanced User Experience: Reflects attention to user-centric design, increasing satisfaction and retention.

### Benefits

- Time-Saving: Reduces the time and effort needed to navigate long pages.
- User-Friendly: Makes the website more intuitive and pleasant to use.
- Inclusive: Supports diverse user needs, adhering to accessibility standards.

### Add ScreenShots

Screenshots of previous work:-
![332186194-b7b10ef3-911a-4da0-a4f0-d13343378128](https://github.com/MAVRICK-1/e-commerce_website/assets/146121869/845f0e67-f201-49d1-9050-dd2fbd22a86e)
![332186184-b2297297-184c-4a61-b303-42c1894856d8](https://github.com/MAVRICK-1/e-commerce_website/assets/146121869/dbd483bf-c7f1-4fcf-a108-c4b8b67342eb)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24.

**Comment by MAVRICK-1** [comment]
@AsmitaMishra24 it's already implemented, look at dev branch

**Comment by AsmitaMishra24** [comment]
> @AsmitaMishra24 it's already implemented, look at dev branch

ok
