### ISSUE TITLE
[Feature Request]: Want to add Auto Detect Location 

### ISSUE THREAD

**Issue by nishant0708** [MAVRICK-1/e-commerce_website#287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Want to Add auto detect location 

### Use Case

through this user manually dont have to add address for delivery

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@nishant0708 not needed
