### ISSUE TITLE
[Feature Request]: Want to Enhance Profile/My Account Page

### ISSUE THREAD

**Issue by nishant0708** [MAVRICK-1/e-commerce_website#289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to Improve UI of this page

### Use Case

This feature Maintains Consinstency of Good user Experience 

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101548649/a2d57ca7-40d7-422c-9029-d382f25e1e2e)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@nishant0708 go ahead, will add level after seeing your pr

**Comment by nishant0708** [comment]
Okay Np.

**Comment by nishant0708** [comment]
Hey @sanket95droid @MAVRICK-1 can you add level tag to it please
