### ISSUE TITLE
[Bug] - The search bar in Hero section is overflowing.

### ISSUE THREAD

**Issue by NilanchalaPanda** [MAVRICK-1/e-commerce_website#29]
## Description
The search bar in hero section of the website is looking fine. But in mobile version the size of the search bar is not optimized and it overflows to the right of the website.

## Steps to Reproduce 
- [ ] Open on mobile to view the bug.

## Screenshots -
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/110488337/24f6c189-77e7-4bb0-824c-852b1ccdaae2)

## Priority
High

## Labels
bug, enhancement, UI/UX, GSSoC'24.

I would love to work on this issue and contribute to it as GSSoC'24 contributor. Looking forward to you reply.

**Comment by MAVRICK-1** [comment]
@NilanchalaPanda okay go ahead, but it will fixed after refreshing

**Comment by NilanchalaPanda** [comment]
Thanks for update @MAVRICK-1, the search bar hides upon refreshing as you said. But we can fix it to display, will work upon that.

**Comment by MAVRICK-1** [comment]
okay i am making it level 3 , go ahead

**Comment by NilanchalaPanda** [comment]
Hey @MAVRICK-1, by any chance do you know where does the `newsLetterBanner` gets hidden in mobile view. Because I not able to get the css where it is getting hidden. I checked in `responsive.css` file and `styles.css` file (specifically for New Letter Banner)

**Comment by MAVRICK-1** [comment]
@NilanchalaPanda go to the clone repository and click ctrl+shift+F and search the word Newsletter , you will get everything related to it

**Comment by NilanchalaPanda** [comment]
I did that before only, but my doubt was the NewsLetterBanner is not hidden anywhere in the file `responsive.css`, but then too it is not visible in mobile version.

**Comment by MAVRICK-1** [comment]
## it's is working fine , i g your facing problem while rendering component
https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/588ea2a9-c8f2-451c-a687-c445a6d7828f

**Comment by Yashc885** [comment]
i would like to resolve this issue
