### ISSUE TITLE
[Bug]: Wishlist empty page view

### ISSUE THREAD

**Issue by shivam2027** [MAVRICK-1/e-commerce_website#292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

"Your wishlist is empty"  overlapping with header section for varying dimensions.

### Expected behavior

Proper positioning required.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/152594323/dc03ebbf-03db-410f-9653-1e5558482d4f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Refresh it
