### ISSUE TITLE
[Bug]: Header section alignment of div is improper for certain dimensions

### ISSUE THREAD

**Issue by shivam2027** [MAVRICK-1/e-commerce_website#293]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Different div of header section at certain dimensions go ups and down.

### Expected behavior

every div should be aligned in straight row.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/152594323/ace7c949-d32e-4733-ad5f-36c58624040f)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
Refresh it ,
