### ISSUE TITLE
[Feature Request]: Adding Legal Pages to the website

### ISSUE THREAD

**Issue by Hemashree21** [MAVRICK-1/e-commerce_website#298]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to work on adding Privacy Policy and Terms and Conditions page. I will also make the page responsive.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/138188163/43c583f0-17e1-458a-8abb-2a62f5e4e2d6)

@MAVRICK-1 can you please assign this to me?

### Use Case

It'll help the users know how the website handles their personal information.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Hemashree21 The issue is already taken, #229
