### ISSUE TITLE
Add Favicons to  Website

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#3]
# Title: Feature Request: Add Favicons to  Website

## Issue Description:
Currently, our React website lacks favicon, which are essential for enhancing user experience, branding, and recognition. Favicon provide a visual identifier for our website, appearing in browser tabs, bookmarks, and other user interface elements. Adding favicons to our React website will contribute to a more polished and professional appearance while improving usability for our visitors.
 
 Favicon link : [Link](https://github.com/MAVRICK-1/e-commerce_website/blob/main/src/assets/images/logo.svg)

**Comment by surendar-05** [comment]
Hey!! Assign this issue to me i want to work on this?under Gssoc'24

**Comment by surendar-05** [comment]
Okayy!

**Comment by divyansh141** [comment]
Please assign this task to me. I want to work on it

**Comment by MAVRICK-1** [comment]
@surendar-05 any update ?

**Comment by MAVRICK-1** [comment]
@divyansh141 if didn't get any response from @surendar-05 within 24 hrs this will be assigned to you

**Comment by divyansh141** [comment]
Okay!

**Comment by surendar-05** [comment]
I completed the half and I try to complete asap

**Comment by MAVRICK-1** [comment]
@divyansh141 go ahead

**Comment by divyansh141** [comment]
Okay, working on it!

**Comment by priyankMS** [comment]
Hey!! Assign this issue to me i want to work on this?under Gssoc'24

**Comment by priyankMS** [comment]
please give me task i want to work on it
