### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by aashkaaaaaa** [MAVRICK-1/e-commerce_website#30]
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/138461600/d5a7cdfc-2ba4-4146-9be9-33055a5915bf)

**Comment by MAVRICK-1** [comment]
@aashkaaaaaa you have to give location access

**Comment by aashkaaaaaa** [comment]
there issue in zoom in/out button

**Comment by MAVRICK-1** [comment]
@aashkaaaaaa okay got it , we are using react leaflet library for the open street map , and zoom in and out button is included in the , you can go through it's document .  
[Map Component ](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/components/map) the map component link . feel free to ask

**Comment by MAVRICK-1** [comment]
@Hemu21 this issue is low priority .

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this to me
