### ISSUE TITLE
[Feature Request]: SCROLLUP BUTTON 

### ISSUE THREAD

**Issue by nisargaa20** [MAVRICK-1/e-commerce_website#301]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Different users have different visual preferences and needs. Providing both light and dark modes ensures that the interface is accessible to a broader audience, including those with visual impairments or light sensitivity.
A scroll-down button (often represented as a downward arrow) can significantly improve the user experience on web pages and applications

### Use Case

Dark mode can reduce eye strain, especially in low-light environments, making it more comfortable for users to read content for extended periods.

Downward arrow can significantly improve the user experience on web pages .

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@nisargaa20 Hey someone is already working on it, #256
If this feature is not added in #256 then I'll assign it to you!!

**Comment by nisargaa20** [comment]
@sanket95droid They are working on dark/light mode. Can I work on Scroll to bottom button

**Comment by sanket95droid** [comment]
@nisargaa20 I'm assigning you this issue, instead of scroll down add a scroll up button.

**Comment by nisargaa20** [comment]
@sanket95droid There is already scrollup button . Do you mean scroll down button?

**Comment by sanket95droid** [comment]
@nisargaa20 Can you refactor scrollup button and aslo implement scroll down?

**Comment by nisargaa20** [comment]
@sanket95droid sure will do that

**Comment by nisargaa20** [comment]
@sanket95droid I have made PR kindly check it out

**Comment by sanket95droid** [comment]
@nisargaa20 Actually we are working on some deployment link issue, once it is done I'll merge your PR dw.
Till then try to make more feature requests if you have any

**Comment by nisargaa20** [comment]
@sanket95droid sure
