### ISSUE TITLE
[Bug]: zoom in and zoom out button 

### ISSUE THREAD

**Issue by BCA-444-9758-Ketan** [MAVRICK-1/e-commerce_website#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

when we scroll the groceries section zoom in and zoom out button is  getting over the other elements

### Expected behavior

IT should to be scrolled with the image

### Add ScreenShots

https://github.com/MAVRICK-1/e-commerce_website/assets/146806880/10e0af62-5f70-442f-bbc6-fe15d8b2a220

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Gamerking177** [comment]
nice @Ketanop321
