### ISSUE TITLE
[Feature Request]: navbar is not alligned properly

### ISSUE THREAD

**Issue by prachita0504** [MAVRICK-1/e-commerce_website#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

as the navbar is main part of the web so its look good .

### Use Case

align navbar properly.

### Add ScreenShots

![Screenshot 2024-06-02 193357](https://github.com/MAVRICK-1/e-commerce_website/assets/139040702/6b672eea-5627-4709-abc0-562e874a0863)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@prachita0504 check the deployment of dev branch it's already rectified [Link](https://nestondcshop.vercel.app/)
