### ISSUE TITLE
[Feature Request]: Chat button and the bottom to top button is not aligned properly in mobile view

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [MAVRICK-1/e-commerce_website#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/125277258/206ba5ed-9f34-4d23-862a-0140f1464040)

### Use Case

in small screen

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@RamakrushnaBiswal okay go ahead
