### ISSUE TITLE
[Feat] : State Management

### ISSUE THREAD

**Issue by Sid-80** [MAVRICK-1/e-commerce_website#31]
## Description
Redux setup is not completed for state management.

**Comment by Sid-80** [comment]
@MAVRICK-1 Shall I add the redux functionality for state management ?

**Comment by MAVRICK-1** [comment]
@Sid-80 that seems a lot of work , it's better divide your task into 2 or 3 part each level 3. also create respective issue regarding the task

**Comment by Sid-80** [comment]
@MAVRICK-1 Sure!

**Comment by Sid-80** [comment]
@MAVRICK-1 Shal I create different slice for auth and cart ?

**Comment by MAVRICK-1** [comment]
@Sid-80 you can start with auth , cart will be migrate from realtime database to firestore after that you can start with cart

**Comment by Sid-80** [comment]
Sure!
