### ISSUE TITLE
[Feature Request]: Home page Footer is not responsvie

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [MAVRICK-1/e-commerce_website#310]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/125277258/2e6c8127-b3db-4eac-865f-57ba00782fc8)

### Use Case

like the social media icons and phone number

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
![Screenshot_2024-06-03-21-49-14-571_com.android.chrome.jpg](https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/02cd6036-5e49-4817-bff9-31195bc10218)
