### ISSUE TITLE
[Feature Request]: To make the "Browse All Categories" dropdown functional

### ISSUE THREAD

**Issue by rohitinu6** [MAVRICK-1/e-commerce_website#313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In the home page, the "Browse All Categories" dropdown is not functioning, which is supposed to be showing all the available categories in a single list.

### Use Case

I would like to make this dropdown a functional one by adding a list of all the available categories in the dropdown menu. 

I would like to make all the above mentioned changes in the code.

### Benefits

This will allow users to find all the available categories in one single place.

### Add ScreenShots

![ONDC Nest](https://github.com/MAVRICK-1/e-commerce_website/assets/113301503/a561e1e9-6289-4be2-a0db-013541f6b93a)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@rohitinu6 deploy the dev branch locally , it's work
