### ISSUE TITLE
[Documentation Update]: Adding Requirements.txt file

### ISSUE THREAD

**Issue by ranamanish674zu** [MAVRICK-1/e-commerce_website#315]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

we can add a Requirements.txt file in the project so it will be useful to understand the project, where we can put all the requirement which we need in the project

### Suggested Change

we need to add a text file only for that where we put all libraries & tools or framework names and it's versions

### Rationale

It will be beneficial to understand the requirment for the project , by seeing the requirement.txt file developer can understand which technology used in the project 

### Urgency

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@ranamanish674zu not needed .
Everything is given in readme.md file
