### ISSUE TITLE
[Feature Request]:  adding SCROLL TO TOP button

### ISSUE THREAD

**Issue by MuraliDharan7** [MAVRICK-1/e-commerce_website#317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I want to add SCROLL TO TOP BUTTON in the page.

### Use Case

Whenever there is a website which has more page, this definitely requires a button which takes us to top of the page.

### Benefits

This will take us to top of the page if we are stuck in between in the website.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@MuraliDharan7  already exists
