### ISSUE TITLE
[Bug]: First section is differed from others.

### ISSUE THREAD

**Issue by MuraliDharan7** [MAVRICK-1/e-commerce_website#318]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/130668745/f557c8e6-d3b9-43c4-a4b7-0b02b8e92ac0)

The first box of this section is different from another box. This should be changed and should be made like others.

### Expected behavior

All the boxes should be same

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/130668745/a1424f8c-aa48-4570-851f-dc83aadafb02)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@MuraliDharan7 go ahead
