### ISSUE TITLE
[Feature Request]: Add forget password page

### ISSUE THREAD

**Issue by MuraliDharan7** [MAVRICK-1/e-commerce_website#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The forget password page is getting to load and I want to add forget password page.

### Use Case

forget password will be helped if the user forgets the password. They can reclaim them using this section

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/130668745/18dda321-6e2c-4829-824e-6c1f5572cca2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@MuraliDharan7 already exists
