### ISSUE TITLE
Sub text UI improvements

### ISSUE THREAD

**Issue by VedantAnand17** [MAVRICK-1/e-commerce_website#32]
**Describe the bug**
![Screenshot_2024-05-11-11-16-24-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MAVRICK-1/e-commerce_website/assets/136731196/97543935-913d-4a15-a198-1e86196bfdb4)
As you can see here, the text is not attractive and bold enough.

**To Reproduce**

1. Go to the home page
2. Click on the triple lines at top
3. Scroll down to Shop section 
4. Click there

**Expected behavior**
The text should be alluring and bold enough that a person shows their attention to it.
**Screenshots**
![Screenshot_2024-05-11-11-16-24-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/MAVRICK-1/e-commerce_website/assets/136731196/d9bf4dd3-c731-4304-81e5-229bcf75e7c4)

**Desktop (please complete the following information):**

- OS: Windows
- Browser Chrome
- Version latest

**Smartphone (please complete the following information):**

- Device: OnePlus 11R
- OS: OxygenOS 14
- Browser Chrome
- Version latest

**Additional context**
Please assign this issue to me, I've participated in several projects and will produce the optimised code in here too.

**Comment by MAVRICK-1** [comment]
@VedantAnand17 okay go ahead it's level 2

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by iamhvsharma** [comment]
Can you assign me this issue?

**Comment by MAVRICK-1** [comment]
@VedantAnand17 any updates ?

**Comment by VedantAnand17** [comment]
Sir I'm changing the text but some things are being broken by that so I'm resolving the issue by debugging it from the code…

**Comment by MAVRICK-1** [comment]
@VedantAnand17 for the  CSS classes must be in  hierarchical structure
