### ISSUE TITLE
[Feature Request]: overlapping subscribe button

### ISSUE THREAD

**Issue by Noopur-Thombare** [MAVRICK-1/e-commerce_website#325]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

subscribe button is overlapping with search so when we write in search it is not visible properly.This problem is not visible in front page but as we go inside different pages is is present.
Using CSS and HTML I can easily fix this issue.
please assign this issue to me with apprepriate Gssoc label.

### Use Case

after solving this issue people can easily see search bar which is currently overlapping and hidden by subscribe button

### Add ScreenShots

![Screenshot 2024-06-04 003820](https://github.com/MAVRICK-1/e-commerce_website/assets/144435206/73c47594-38a9-4a67-9139-0f6af33524a0)

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Noopur-Thombare Hey I dont see any such bug in the project.
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/77754719/16fe495e-7813-4166-9d2a-cc32237da0b9)
I think you need to recheck
