### ISSUE TITLE
[Bug]: In featured categories, the images added have blur text

### ISSUE THREAD

**Issue by divyalaldinani** [MAVRICK-1/e-commerce_website#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/82147067/06a22c28-7b44-47b4-b892-62d79c35ff94)
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/82147067/82bd30d6-b84c-4071-bc25-5df7d6430162)

Here the images are of low quality, thus we can change these images by adjusting sharpness, contrast etc.

### Use Case

I will adjust the features (contrast, sharpness) of these images to make them look clear and of high quality.

### Benefits

Making images look clear on a web page offers several significant benefits, enhancing both user experience and site performance. 

### Add ScreenShots

added above

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by divyalaldinani** [comment]
> Hi there!
> 
> Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible.
> 
> Please note that this is the project owner, @MAVRICK-1. I won't be available for 3-4 days and will reply to every PR after May 26. Thank you for your cooperation.

may 26 has passed, its june 4, i hope Project owner is available as of now

**Comment by sanket95droid** [comment]
@divyalaldinani If you have any query text me!!
Go ahead work on this, not just change the sharpness and contrast, change the images completely if you can.
Also this looks more like a BUG than a FEATURE REQUEST.

**Comment by divyalaldinani** [comment]
> @divyalaldinani If you have any query text me!! Go ahead work on this, not just change the sharpness and contrast, change the images completely if you can. Also this looks more like a BUG than a FEATURE REQUEST.

yeah i think the images suit well as per the theme of web page and are visually appealing, that's why we shouldn't replace them

**Comment by divyalaldinani** [comment]
also can you change the label maybe? to BUG?


> @divyalaldinani If you have any query text me!! Go ahead work on this, not just change the sharpness and contrast, change the images completely if you can. Also this looks more like a BUG than a FEATURE REQUEST.

**Comment by divyalaldinani** [comment]
> @divyalaldinani If you have any query text me!! Go ahead work on this, not just change the sharpness and contrast, change the images completely if you can. Also this looks more like a BUG than a FEATURE REQUEST.

also can you assign me this issue? so that i can raise a PR

**Comment by divyalaldinani** [comment]
@sanket95droid can you check the PR?
