### ISSUE TITLE
improving navbar

### ISSUE THREAD

**Issue by mahek0620** [MAVRICK-1/e-commerce_website#328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

styling navbar to make it look attractive 

### Suggested Change

.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@mahek0620 Can you provide more description how are you going to make it more attractive?
