### ISSUE TITLE
adding contributors page

### ISSUE THREAD

**Issue by mahek0620** [MAVRICK-1/e-commerce_website#329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding profile photo of all contributors

### Use Case

It fosters a sense of community around the project. Contributors can see who else is involved, fostering connections and potentially leading to collaborations or networking opportunities. It serves as a form of documentation, showing the evolution of the project and who has been involved at different stages. This can be useful for future contributors or for anyone interested in the project's history.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@mahek0620 Already present please check the project.
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/77754719/9d97b070-8fd9-4ca7-a643-a2f82f17500a)
