### ISSUE TITLE
[Bug]: scroll to top button not visible

### ISSUE THREAD

**Issue by sau-mili** [MAVRICK-1/e-commerce_website#331]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I wish to fix the UI 

### Expected behavior

it should be visible

### Add ScreenShots

![Screenshot 2024-06-04 121623](https://github.com/MAVRICK-1/e-commerce_website/assets/146661411/c1791b83-6034-419f-839f-647dea5515ea)

### On which device are you experiencing this bug?

Linux, Chrome, Windows

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@sau-mili OK
