### ISSUE TITLE
[Bug]:  Enhance the UI in the shop section.

### ISSUE THREAD

**Issue by parikhitritgithub** [MAVRICK-1/e-commerce_website#336]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The elements and words in the shop section are not aligned, so we need to enhance the UI.

### Expected behavior

 just need to improve the UI.

### Add ScreenShots

![Screenshot 2024-06-04 185935](https://github.com/MAVRICK-1/e-commerce_website/assets/124444610/e8cfc799-8731-4ff3-8bf6-e16a621be6b1)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@parikhitritgithub Can you recheck this bug??

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.
