### ISSUE TITLE
[Bug]: Sign in and signup

### ISSUE THREAD

**Issue by kashnx** [MAVRICK-1/e-commerce_website#341]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

user can only register using firebase authentication. I want to connect it with a mongodb database so that user can register with password and email.

### Expected behavior

.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@kashnx we already use firestore for that
