### ISSUE TITLE
[Feature Request]: Footer UI for Mobile devices 

### ISSUE THREAD

**Issue by Sypher0Dronzer** [MAVRICK-1/e-commerce_website#345]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

On resizing the screen the texts get smaller along with the screen-size, also for mobile devices the text is not visible and some content goes beyond the screen making it inaccessible. 

**There has been an issue earlier for footer UI for browser screens but nor for responsiveness**

Please assign this issue to me @MAVRICK-1 , I have gone through the code and found the places that need to be changed in order to obtain the proper functionality

### Use Case

This would be highly beneficial for users at smaller screens such as mobile users in particular.

### Benefits

This would be highly beneficial for users at smaller screens such as mobile users in particular.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/83546205/bd837262-e13e-4182-bfd6-76593fdd5943)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@Sypher0Dronzer okay go ahead
