### ISSUE TITLE
[Feature Request]: Use Glassmorphism in Navbar of Mobile device

### ISSUE THREAD

**Issue by Sypher0Dronzer** [MAVRICK-1/e-commerce_website#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current navbar lacks style so i want to implement glassmorphism or Frost glass effect to it to make it look even more cooler

### Use Case

Its for better user experience

### Benefits

attract more audience

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/83546205/6f7e3c33-a175-4b21-87f4-3769d214f2cb)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Sypher0Dronzer Go ahead
