### ISSUE TITLE
[Bug]: Customer support Number not visible 

### ISSUE THREAD

**Issue by Sypher0Dronzer** [MAVRICK-1/e-commerce_website#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The customer support number is not visible at home screen

### Expected behavior

It must be visible to user.

please assign this issue to me @MAVRICK-1 

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/83546205/0953a82d-511b-4843-97f8-e498f4fbe53c)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Sypher0Dronzer** [comment]
please assign this issue to me @MAVRICK-1

**Comment by MAVRICK-1** [comment]
@Sypher0Dronzer go ahead use a random number
