### ISSUE TITLE
Add functionality to contact page

### ISSUE THREAD

**Issue by ananyag309** [MAVRICK-1/e-commerce_website#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

1) I will like to add java script code for contact form to accept user details
2) As soon as user will submit the code it will display a confirmation message 
3) in contact form instead of " sign in" i will replace it with submit 

![new issue](https://github.com/MAVRICK-1/e-commerce_website/assets/145869907/a08441a7-f828-4c88-bb41-f82f757e8a6a)

### Suggested Change

I will add js code to add functionality to the contact page.

### Rationale

@MAVRICK-1 please assign this issue to me under Gssoc.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Gokilp** [comment]
please issue  issue to Under Gssoc 24

**Comment by MAVRICK-1** [comment]
@ananyag309 functional is already added , API is not added till now
