### ISSUE TITLE
[Documentation Update]: Update file

### ISSUE THREAD

**Issue by srinjayi-sarkar** [MAVRICK-1/e-commerce_website#358]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

The current LEARN.md file looks somewhat like README.md.

### Suggested Change

I would like to update the LEARN.md file for this project. Kindly assign this task to me under GSSoC'24 with required labels. @mav

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@Passionatelytoooadorable not needed
