### ISSUE TITLE
[Feature Request]:  Improve the SEO of the home page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [MAVRICK-1/e-commerce_website#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The current SEO (Search Engine Optmization ) is 35 that is not good but i will try to increase it minimum by 15 .
It can be done by taking help from the internet doing lot of research and using semantics tags like  (Section , Main , Article ) etc .

### Use Case

This helps the website to rank on the Search Engine 

### Add ScreenShots

![Screenshot 2024-06-09 104016](https://github.com/MAVRICK-1/e-commerce_website/assets/118350936/1126b2f6-8dc3-43ff-8b67-bfda28739bfa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@Ayushmaanagarwal1211 Good Contribution, go ahead
