### ISSUE TITLE
Nav bar: Blog Section can be added and "browse all categories" can have functionality

### ISSUE THREAD

**Issue by Divyanshu832** [MAVRICK-1/e-commerce_website#37]
**Is your feature request related to a problem? Please describe.**
In our navigation bar, "Browse all categories" button doesn't have any functionality. Clicking on it does nothing. And "blog" also is not taking the users anywhere.

**Describe the solution you'd like**
I want to add functionality to "Browse all categories" button, so that a dropdown appears listing all the category of items or services we are presenting.
And I want to redirect the user from "Blog" to a page where blogs are there that represents our initiatives or our services and our future expansions.

**Additional context**
I would prefer to use "alpine.js" for dropdown but I can do it through react too... if you're concerned with alpine.js

**Comment by MAVRICK-1** [comment]
@Divyanshu832 blog page is not created yet , I likew your idea , go ahead , level 3

**Comment by Divyanshu832** [comment]
Alright, Do you want me to work on "Browse all category" button too?
And How many of the blogs initially I should attach to the page?

**Comment by MAVRICK-1** [comment]
@Divyanshu832 you attach 3 blog on three categories make it responsive , add  styling and pictures you can also use material ui for that. we will discuss about the "Browse all category" button in another issue

**Comment by Divyanshu832** [comment]
So you want like 3 blogs each of categories like, Fashion, Groceries and Electronics?

**Comment by anwesha2002** [comment]
@MAVRICK-1 
I am a GSSOC'24 contributor. I would like to work on  "Browse all category" functionality. Please you assign this to me

**Comment by MAVRICK-1** [comment]
@Divyanshu832 any update ? or i will assign this to @anwesha2002
