### ISSUE TITLE
[Feature Request]:  Addition of error 404 page

### ISSUE THREAD

**Issue by taneeshaa15** [MAVRICK-1/e-commerce_website#371]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Error 404 will inform the user about removed pages or wrong url.

### Use Case

Users willbe directed to homepage without wasting much time.

### Benefits

1.) Time Management.
2.) Enhancement of UI.

### Add ScreenShots

![md](https://github.com/MAVRICK-1/e-commerce_website/assets/157527085/b67bbf84-8045-44be-9eaf-599786526c8c)
Will look like this (Not exactly).

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by taneeshaa15** [comment]
@MAVRICK-1 Please assign me this issue under gssoc'24 level 2.

**Comment by MAVRICK-1** [comment]
@taneeshaa15 already exists
