### ISSUE TITLE
[Bug]: Support centre number not much visible.

### ISSUE THREAD

**Issue by taniya542** [MAVRICK-1/e-commerce_website#377]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The support center number (1900-888)is not visible clearly due to the color set.

![Number ](https://github.com/MAVRICK-1/e-commerce_website/assets/143064148/d5305b22-ec4c-4c37-b8dc-8dd13be18552)

### Expected behavior

It should be visible clearly, can be rectified by using specific color pallete.Please assign this issue to me under GSSOC 24

### Add ScreenShots

![Number ](https://github.com/MAVRICK-1/e-commerce_website/assets/143064148/04e9fdea-e6f5-49d0-b1b8-e5e93bfc2740)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by guneetdewangan9** [comment]
I would like to solve this issue. Please assign me this issue under GSSoC'24 to contribute to this project.

**Comment by taniya542** [comment]
Please assign this issue to me under GSSOC 24

**Comment by MAVRICK-1** [comment]
@taniya542 did you run it locally ?
