### ISSUE TITLE
[Bug]: The carousel does not cover the width

### ISSUE THREAD

**Issue by Stiffpixels** [MAVRICK-1/e-commerce_website#383]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The carousel on the homepage has blank space on the right edge.

### Expected behavior

The carousel should fill the width completely of the container.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/32983571/d8203366-f09f-4756-800a-4b92c0a5ac19)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@Stiffpixels try to run it locally
