### ISSUE TITLE
[Feature Request]:  Add Signup/signin page Responsive UI 

### ISSUE THREAD

**Issue by DevGajjar28** [MAVRICK-1/e-commerce_website#385]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add signup page and sign in page to login the users 

### Use Case

Adding this UI it will help to login user, track there orders, customizes services, user review and feedback 

### Add ScreenShots

![Screenshot 2024-06-11 113101](https://github.com/MAVRICK-1/e-commerce_website/assets/145287513/94084b80-4fdf-41d6-910d-6f4b83fa247f)
![Screenshot 2024-06-11 113427](https://github.com/MAVRICK-1/e-commerce_website/assets/145287513/c03c7ca3-60d2-4859-9b75-7b4b2b559caa)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MAVRICK-1** [comment]
@DevGajjar28 not needed we already got one
