### ISSUE TITLE
Add "Navigation Links" to the "FAQ Section" in Footer

### ISSUE THREAD

**Issue by MastanSayyad** [MAVRICK-1/e-commerce_website#390]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

The current website has an FAQ section that provides valuable information to users, but there are no navigation links available to easily access this section. This makes it difficult for users to find and navigate to the FAQ section. I suggest adding navigation links in the header, footer, and possibly in a prominent location on the homepage to improve accessibility.

### Expected behavior

To improve user experience, navigation links to the FAQ section should be added to the footer on the homepage. This will make it easier for users to find and access frequently asked questions

### Add ScreenShots

**like this:**

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/8576c2e5-97e9-43ec-ad01-1a41aa95fd20)

please assign this issue to me under gssoc.

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Ankitkdwivedi** [comment]
I want to handle this issue kindly give it to me.

**Comment by MAVRICK-1** [comment]
@MastanSayyad go ahead
