### ISSUE TITLE
Feature 🌟: FAQ Section Layout Improvement

### ISSUE THREAD

**Issue by aslams2020** [MAVRICK-1/e-commerce_website#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1,
Here is the feature I want to suggest - 
The **Frequently Asked Questions** section of the website currently **lacks padding and margin**, resulting in a crowded appearance with no spacing between the FAQ items. 
Additionally, the section is not centered, which affects the overall visual appeal and user experience.

### Use Case

**Current Appearance:**
- No padding or margin around FAQ items.
- FAQ section aligned to full width of the page.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/131389695/c8a5e00e-dc09-4ae7-bc06-813229b5d7da)

**Expected Appearance:**
- Adequate padding and margin around each FAQ item.
- FAQ section centered within the page for better aesthetics.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/131389695/df8ccc4d-75f0-4785-91c4-ae18d16e6873)

### Benefits

- Improved Readability
- Enhanced Visual Appeal
- Better User Experience
- Increased Engagement

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@aslams2020 Go ahead
