### ISSUE TITLE
Add "Licensing" Page Reflecting "MIT License" in Footer

### ISSUE THREAD

**Issue by MastanSayyad** [MAVRICK-1/e-commerce_website#397]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1 and @sanket95droid 

The current website lacks a dedicated **licensing page,** The repository is licensed under the MIT License, which clearly states under that the project is distributed. A licensing page should be added to the website reflecting the MIT License to ensure legal clarity and transparency for users and contributors.

I would like to add **Licensing Page which reflects MIT license** for the website:

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/7f5bb35f-8363-4597-afaf-bc5b645adccc)

### Use Case

- User Navigates to the website.
- User Clicks on the "License" link in the website's navigation menu.
- System Displays the licensing page with the full text of the MIT License.
- The user can easily find and read the licensing terms under which the project is distributed.

### Benefits

- Transparency 
- Legal Clarity
- Professionalism

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by MastanSayyad** [comment]
@MAVRICK-1 @dinxsh @sanket95droid please take a look at this issue and assign me

**Comment by dinxsh** [comment]
and how do you intend to show the license details

**Comment by MastanSayyad** [comment]
Like this: @dinxsh 

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101971980/81b9474b-4078-4d69-b840-a837a5136fcd)

**Comment by MAVRICK-1** [comment]
@MastanSayyad thanx but not needed
