### ISSUE TITLE
Title: Implement ESLint 

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#4]
# Title: Implement ESLint 

## Issue Description:
As our React project grows, maintaining code quality becomes increasingly important. One way to ensure consistent code style and catch potential errors early is by implementing ESLint. ESLint is a widely used tool that helps enforce coding standards and identify common programming mistakes.

By integrating ESLint into our project, GitHub contributors will benefit from automatic code linting and error highlighting directly within their development environments. This will streamline the code review process, improve code readability, and foster better collaboration among team members.

This issue involves configuring ESLint for our React project, defining coding standards and rules tailored to our codebase, and providing documentation on how contributors can set up ESLint in their local development environments.

## Additional Information:
- Our project uses React for front-end development.
- We aim to improve code quality and consistency through the implementation of ESLint.
- Feel free to ask questions or seek clarification on any aspect of this issue.

**Comment by helloworld-chhanda** [comment]
I am a contributor of the GSSoC' 24. I want to pick this task. Please assign this to me.

**Comment by MAVRICK-1** [comment]
@helloworld-chhanda GSSoC  Period Starts from tomorrow , First come First serve basis it will be assign to you

**Comment by helloworld-chhanda** [comment]
Can I pick this now?

**Comment by MAVRICK-1** [comment]
@helloworld-chhanda it's  assigned

**Comment by MAVRICK-1** [comment]
@helloworld-chhanda any updates ?
I am upgrading this to level3

**Comment by helloworld-chhanda** [comment]
Please review my PR 
https://github.com/MAVRICK-1/e-commerce_website/pull/69
