### ISSUE TITLE
[Bug] 🐞:  Move "Scroll to Bottom" Button to the Left Side

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [MAVRICK-1/e-commerce_website#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @MAVRICK-1 and @sanket95droid 

Currently, the "Scroll to Bottom" button is located on the right side of the website, which is not convenient due to the presence of other buttons. For better accessibility and usability, it would be beneficial to move the "Scroll to Bottom" button to the left side.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/163530398/2df367b9-fa47-4fcc-861d-c0ea6515a99e)

### Expected behavior

The "Scroll to Bottom" button should be located on the left side to avoid clutter and enhance user convenience.

### Add ScreenShots

**For Example like this**

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/163530398/fa94c5e0-0ac2-4f89-b2b1-2aee47ef6241)

Could you please assign me this issue under Gssoc24

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
hi @RadhikaMalpani1702 , could you possibly make it so its to the left of the scroll to top button with styles similar to it (heights margins etc)?
