### ISSUE TITLE
Redesign "Vertical Scrollbar" to Match "Website Theme

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [MAVRICK-1/e-commerce_website#401]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1 and @sanket95droid 

The current vertical scrollbar does not align with the website's overall design theme. For a more cohesive and visually appealing user experience, the scrollbar should be redesigned to match the website's theme.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/163530398/f63fed96-5b83-4aeb-8924-1354613cef26)

I would like to take on this task could you please assign this issue to me under GSSOC 24

### Use Case

- Improved Aesthetics
- Professional Appearance
- Enhanced User Experience
- Increased User Engagement

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
assigned @RadhikaMalpani1702 looking forward to this
