### ISSUE TITLE
[Feature Request]: Addition of a Circular Animated Cursor

### ISSUE THREAD

**Issue by HishitaGupta** [MAVRICK-1/e-commerce_website#406]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of a Circular Animated Cursor to enhance the UI of the website.

### Use Case

Will enhance the UI of the website.

### Benefits

Will add interactivity to the website.

### Add ScreenShots

https://github.com/MAVRICK-1/e-commerce_website/assets/159264060/8fa512e6-d93e-448c-b668-3338f7a5db38

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
we dont need this as of now, thanks!
