### ISSUE TITLE
[Feature Request]: Addition of Google Translator in the footer

### ISSUE THREAD

**Issue by HishitaGupta** [MAVRICK-1/e-commerce_website#409]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Addition of Google Translator in the footer .

### Use Case

To make the app multilingual and more accessible.

### Benefits

To make the app multilingual and more accessible.

### Add ScreenShots

![Screenshot 2024-06-21 115052](https://github.com/MAVRICK-1/e-commerce_website/assets/159264060/dc5eebca-de5c-4746-9eb6-4b5b60afb17e)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
would be a great feature, have assigned it to you @HishitaGupta
