### ISSUE TITLE
[Bug]:   correcting the ui of sign up or register new user page as user unable to see the enter otp section

### ISSUE THREAD

**Issue by ayushpatel1248** [MAVRICK-1/e-commerce_website#418]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

1. signup or register page is ui is not correct as well as not responsive 
2. due to which is user is unable to register 
3. as user can see any field to enter the otp 
4. this is causing the issue to register a user

### Expected behavior

- proper card should be visible so that user can register easily 
- and otp section should be visible 

### Add ScreenShots

<img width="1440" alt="Screenshot 2024-06-25 at 12 57 56 AM" src="https://github.com/MAVRICK-1/e-commerce_website/assets/127100604/37a20b53-0e26-4413-a660-6f0e8cf2423a">

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by sanket95droid** [comment]
@ayushpatel1248 already taken
