### ISSUE TITLE
Adding profile in navbar

### ISSUE THREAD

**Issue by mahek0620** [MAVRICK-1/e-commerce_website#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The goal is to introduce a profile section in the navbar of our e-commerce website. This feature will allow users to access their account details, orders history, saved items, and other personalized settings directly from any page of the site.

### Use Case

.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
not relevant for an ecommerce website, sorry!

**Comment by dinxsh** [comment]
have assigned it to you @mahek0620 , looking forward to this issue
