### ISSUE TITLE
[Feature Request]:  changing text colour green of navbar items on hover

### ISSUE THREAD

**Issue by dhairyagothi** [MAVRICK-1/e-commerce_website#425]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

changing text colour to green
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/142989448/e8715f28-2259-41fc-bf28-470793bc0eab)

### Use Case

makes it beautiful

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
would look good, have assigned the issue @dhairyagothi
