### ISSUE TITLE
[Bug]: Email section is colliding

### ISSUE THREAD

**Issue by MuraliDharan7** [MAVRICK-1/e-commerce_website#426]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

E mail section is colliding with the background image section.

### Expected behavior

The email section should be positioned somewhere else.

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/130668745/c7aa181b-0cc7-4eda-b79b-f133f02eccdf)

### On which device are you experiencing this bug?

Windows

### Record

- [X] I have read the Contributing Guidelines
- [x] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
have assigned, looking forward to getting this issue @MuraliDharan7
