### ISSUE TITLE
Featured catagries cards setup 

### ISSUE THREAD

**Issue by Azadak12** [MAVRICK-1/e-commerce_website#43]
In the "Featured Categories" section, there are three different categories: groceries, electronics, and fashion. However, the "Groceries" card is not aligned with the other two cards, and it lacks a hover effect. This inconsistency affects the overall appearance of the UI i mean there should hover on only one card which we are focusing
<img width="302" alt="cone" src="https://github.com/MAVRICK-1/e-commerce_website/assets/107694562/a4b554a6-88b0-4cd2-9d65-7cad751e876a">
.

**Comment by MAVRICK-1** [comment]
@Azadak12 Groceries item has been selected by default so they are not align and hover effect is working fine

**Comment by Azadak12** [comment]
Okie fine
