### ISSUE TITLE
[Documentation Update]: Enhancement of Contributing.md

### ISSUE THREAD

**Issue by PradnyaGaitonde** [MAVRICK-1/e-commerce_website#435]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Images along with github contribution instructions are missing and the repository name mentioned in the instructions is worng.

### Suggested Change

I would like to add images to the github contribution instructions in contributing.md to guide contributors to understand the instructions efficiently.
Also, would like to make a few corrections in the instructions like the repository name that is wrong. 

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/116059908/6d29e777-b5d8-4536-bf8b-32d8560fcf56)

### Rationale

Would help in better understanding and following of the instructions.

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
assigned @PradnyaGaitonde looking forward to this issue!

**Comment by malvika-sinha** [comment]
I want to resolve the issue, kindly assign me the task
