### ISSUE TITLE
Fixing navbar text color in mobile view

### ISSUE THREAD

**Issue by dhairyagothi** [MAVRICK-1/e-commerce_website#436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

![Screenshot_20240629_223904](https://github.com/MAVRICK-1/e-commerce_website/assets/142989448/24c103c3-6901-47f9-9b2c-9127203eb7c8)

Fixing text colour in mobile view 

### Expected behavior

Colour of text should be fixed in mobile view

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
assigned the issue @dhairyagothi , looking forward to this

**Comment by dhairyagothi** [comment]
Sure i will make a PR asap

**Comment by dhairyagothi** [comment]
@dinxsh please check and merge PR under gssoc
