### ISSUE TITLE
[Bug]: Contact Us Not Linked

### ISSUE THREAD

**Issue by pani2004** [MAVRICK-1/e-commerce_website#439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Contact us is not linked in footer

### Expected behavior

On clicking contact us it should redirect to contact us page

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by pani2004** [comment]
@MAVRICK-1 @sanket95droid Can I work on this?

**Comment by dinxsh** [comment]
not linked where, kindly mention. also being worked on in another issue for the footer part, sorry!

**Comment by pani2004** [comment]
@dinxsh on clicking contact us it should redirect to the contact us page.
