### ISSUE TITLE
[Bug]: cannot see the words after with

### ISSUE THREAD

**Issue by UtkarshBirla28** [MAVRICK-1/e-commerce_website#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

........

### Expected behavior

words after with in chatbot cannot be seen

### Add ScreenShots

![Screenshot (142)](https://github.com/MAVRICK-1/e-commerce_website/assets/96072228/6798ee87-f188-4f00-b3f3-959277775e14)

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
not required, its hosted by botpress. thank you!
