### ISSUE TITLE
[Bug]: No signup button 

### ISSUE THREAD

**Issue by UtkarshBirla28** [MAVRICK-1/e-commerce_website#444]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

No signup button and OTP input box

### Expected behavior

.......

### Add ScreenShots

![Screenshot (143)](https://github.com/MAVRICK-1/e-commerce_website/assets/96072228/44999608-47df-4018-a978-3780e477cb2b)

### On which device are you experiencing this bug?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
add it in the sign in page towards the lower side of the card, will assign it to you, sign in and sign up card ui is a bit messed too fix that as well @UtkarshBirla28

**Comment by tkshsbcue** [comment]
can you please assign this issue to me @dinxsh

**Comment by UtkarshBirla28** [comment]
@dinxsh someone has already fixed the signup and signin page 

In repo the pages are fixed but in the main website which is deployed there the signinpage is bit messed up

**Comment by dinxsh** [comment]
@UtkarshBirla28 could you add some screenshots then
