### ISSUE TITLE
[Feature Request]: Footer Not properly alinged

### ISSUE THREAD

**Issue by nishant0708** [MAVRICK-1/e-commerce_website#446]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

want to fix alignment of footer

### Use Case

it will increase look of website

### Add ScreenShots

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/101548649/091bf733-235d-4b44-b606-cfb2b0f1517c)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
redundant, thank you!
