### ISSUE TITLE
BUG :  Displaying Sign In Page While User Is Already Logged In

### ISSUE THREAD

**Issue by CoderSwarup** [MAVRICK-1/e-commerce_website#45]
**Describe the bug**
after user successfully logged in into the website  the user still access the sign in and sign up page 
That user is create a new account or log in with another account still their is logged in 

**To Reproduce**

1. Log in to the website using valid credentials.
2. After successful login, attempt to access the Sign In page again.
3. Notice that the Sign In page remains accessible instead of redirecting the user elsewhere.

**Expected behavior**

After the User Logged In Sign in and Sign Up page will not Accessible 

**Screenshots**
![ERROR](https://github.com/MAVRICK-1/e-commerce_website/assets/128630311/add1728e-a966-4d95-9bbc-5dca5814cde4)

Please Assign Me this issue , i want to work on this

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MAVRICK-1** [comment]
@CoderSwarup okay go ahead
