### ISSUE TITLE
Feature✨ : Add a Feedback Form/Page to the Website

### ISSUE THREAD

**Issue by aslams2020** [MAVRICK-1/e-commerce_website#452]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Hey @MAVRICK-1 , @dinxsh and @sanket95droid ,

I would like to add a feedback form/page to the website. 
Currently there is no Feedback form in the website, As 

To improve user experience and gather valuable insights from visitors, i suggest to add a feedback form/page to the website. This form will allow users to provide their opinions, report issues, and suggest improvements directly.

For example like this:

![image](https://github.com/harshalhonde21/EcommerceSpectastyle/assets/131389695/77e4f6dd-2b73-438c-8e71-a3d3ef6c1910)

I will add Link to the Feedback Page in the Website's Footer.

### Use Case

Here's How will it work - 
- User Clicks on the "Give Feedback" button.
- System Displays the feedback form as a popup.
- User Fills out the feedback form, providing optional name and email, selecting the type of feedback, and entering comments.
- Clicks the "Submit" button on the form.
- Displays a confirmation message indicating the feedback was submitted successfully.
- Closes the feedback form popup.

Could you please Assign me this issue ?

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by dinxsh** [comment]
being worked on #427, you can try working on it though
