### ISSUE TITLE
BUG: Mobile Navbar missing 

### ISSUE THREAD

**Issue by Sakhi29** [MAVRICK-1/e-commerce_website#46]
**Describe the bug**
On opening the website on mobile resolution, the navbar goes missing.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/106910881/b490e7dc-3d13-48ab-825f-de7747dc3988)
 
No navbar found in mobile.
Assign this issue to me under GSSoC.

**Comment by MAVRICK-1** [comment]
@Sakhi29 refresh the page . the problem will get fixed

**Comment by Sakhi29** [comment]
But why does it works like this? Like after making one refresh??

**Comment by MAVRICK-1** [comment]
@Sakhi29 that's the issue regarding Material ui, but it works fine  in the real word, because we cannot dynamically change the width.

**Comment by Sakhi29** [comment]
Maybe if you would have used Tailwind CSS rather than normal CSS, this issue wouldn't have appeared.

**Comment by MAVRICK-1** [comment]
@Sakhi29 we are using tailwind in 80 % of the project , you can work on #50 , if you want

**Comment by Sakhi29** [comment]
Okay Sure, will work on it. Please assign it to me.

**Comment by MAVRICK-1** [comment]
@Sakhi29 you need to comment on that issue to get assigned
