### ISSUE TITLE
Search bar is not responsive 

### ISSUE THREAD

**Issue by GOURAVSINGH19** [MAVRICK-1/e-commerce_website#47]
Search bar in not responsive which is not look  good. Can you assign this issue to me.

**Screenshots**

https://github.com/MAVRICK-1/e-commerce_website/assets/120244528/ba9327c6-7a6f-40c6-9fe3-6d5bcdc11c3e

**Comment by MAVRICK-1** [comment]
@GOURAVSINGH19 Refresh the page it will get fixed
