### ISSUE TITLE
Change Page title 

### ISSUE THREAD

**Issue by BHS-Harish** [MAVRICK-1/e-commerce_website#48]
Hello @MAVRICK-1 

Your page title looking like default React App and favicon also default one.

![Screenshot 2024-05-11 181824](https://github.com/MAVRICK-1/e-commerce_website/assets/114602603/44aa46ca-cffd-4916-9d11-b2d6c9220c79)

Please assign this issue to me
Let me change page title as project name and favicon as well.

Thanks in advance

**Comment by MAVRICK-1** [comment]
@BHS-Harish thanks for the suggestion but this issue is already listead #3

**Comment by MAVRICK-1** [comment]
@BHS-Harish  you can work on the title

**Comment by BHS-Harish** [comment]
Thanks for assigned the issue to me @MAVRICK-1
