### ISSUE TITLE
Migrate Product and Seller Registration Form Data Storage from Realtime Database to Firestore in Firebase

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#5]
# Title: Migrate [Product](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/AddProd) and [Seller Registration](https://github.com/MAVRICK-1/e-commerce_website/blob/main/src/pages/SellerRegistration/index.js) Form Data Storage from Realtime Database to Firestore in Firebase

## Issue Description:
Our current solution for storing data from product and seller registration forms relies on Firebase Realtime Database. However, we recognize the benefits of migrating to Firestore, Firebase's scalable and feature-rich NoSQL database.

Migrating our data storage to Firestore will improve scalability, provide better querying capabilities, and offer real-time updates, ensuring a more robust and future-proof solution for our platform.

This issue involves migrating the backend logic of our registration forms to interact with Firestore instead of the Realtime Database. It also requires updating relevant client-side code to communicate with Firestore endpoints.
## Tasks:
- Research Firestore database structure and data modeling best practices.
- Plan the migration strategy, including any necessary data schema changes.
- Update client-side code to send data to Firestore endpoints.
- Thoroughly test the migration to ensure data integrity and functionality.
- Update documentation to reflect the changes made and provide guidance for future development.
- Coordinate with the backend and frontend teams to ensure a smooth transition.

## Additional Information:
- Our backend is built using Firebase Functions.
- The frontend of our product and seller registration forms is developed using React.
- The assignee will be granted access to the Firebase console for managing Firestore.
- Feel free to ask questions or seek clarification on any aspect of this issue.

**Comment by dev-rsiva** [comment]
I want to work on this. I request that you assign it to me. I think I have enough firestore experience to implement this. Let me do it.

**Comment by dev-rsiva** [comment]
Email: dev.rsiva@gmail.com

**Comment by MAVRICK-1** [comment]
@dev-rsiva this will be assign to you after completing #6

**Comment by dev-rsiva** [comment]
Okay

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this issue to me. why because you mentioned will be assigned. he is working on one issue. So can you please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@Hemu21 Do you have any prior knowledge of Firebase?

**Comment by Hemu21** [comment]
@MAVRICK-1 I had completed the code for products and seller registration forms. Does I need to save the all previous data existed in realtime database to firestore database or that data is just for testing.

**Comment by MAVRICK-1** [comment]
No you don't need to save the previous data

**Comment by MAVRICK-1** [comment]
@Hemu21 you didn't raise ant PR ?

**Comment by Hemu21** [comment]
@MAVRICK-1 Now I raised the PR. can you please check it.
