### ISSUE TITLE
Improve Appearance and Fix Horizontal Overflow in About Page

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#50]
## Issue: Improve Appearance and Fix Horizontal Overflow in About Page

<img width="942" alt="Screenshot 2024-05-11 185454" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/d5fcbc0d-7877-43a4-b6d3-3f247a84efcd">

### Description
The current state of the About Us page needs enhancement to improve its visual appeal and address horizontal overflow issues. Currently, the layout seems unattractive and causes horizontal scrolling, which impacts user experience negatively. 

### Expected Behavior
- The About Us page should have a visually appealing layout.
- The content should be well-structured and easy to read.
- Horizontal overflow issues should be fixed to prevent unnecessary scrolling.

### Tasks
1. **Design Improvement:**
   - Enhance the visual design of the About Us page to make it more aesthetically pleasing.
   - Optimize the layout to ensure it looks visually balanced and professional.

2. **Content Organization:**
   - Review and reorganize the content to make it more concise and engaging.
   - Ensure that the information is presented in a clear and structured manner.

3. **Fix Horizontal Overflow:**
   - Identify the elements causing horizontal overflow.
   - Adjust CSS styles or layout properties to prevent horizontal scrolling.

### Additional Information
- The About Us page is a critical component of our website, as it provides visitors with information about our organization, team members, and mission.
- Improving the appearance and functionality of this page will enhance the overall user experience and reflect positively on our brand image.

### Priority
Medium

### Labels
enhancement, design, usability

### Assignee
[Assignee's GitHub Username]

### Milestone
[Milestone Name or Version]

**Comment by Hemu21** [comment]
@MAVRICK-1  can you please assign it to me.

**Comment by MAVRICK-1** [comment]
@Hemu21 I got another issue for you , you have to migrate cart db from realtime to firestore

**Comment by Hemu21** [comment]
Ok

**Comment by Sakhi29** [comment]
Can, you please assign the issue to me @MAVRICK-1

**Comment by anshumanmondal2006** [comment]
Hello @MAVRICK-1 I too wish to work on this issue. Could you please assign it to me as well?

**Comment by MAVRICK-1** [comment]
@anshumanmondal2006 If i did get any updates on the issue by @Sakhi29 with a day , then this will be assigned to you
