### ISSUE TITLE
 Migrate Cart Database from Realtime Database to Firestore

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#51]
### Description
The current implementation of the cart database relies on a Realtime Database, which has served its purpose well. However, to leverage the benefits of scalability, improved querying capabilities, and real-time updates offered by Firestore, it's essential to migrate the cart database to Firestore.

### Expected Behavior
- The cart functionality should remain intact after the migration.
- Users should be able to add, remove, and update items in their cart without any disruption.
- The migration process should be seamless, with minimal downtime for the cart functionality.

### Tasks
1. **Data Migration:**
   - Export existing cart data from the Realtime Database.
   - Import the exported data into Firestore, ensuring data integrity and consistency.

2. **Code Refactoring:**
   - Modify existing code to interact with Firestore instead of the Realtime Database.
   - Update database read and write operations to use Firestore APIs.

3. **Testing and Validation:**
   - Conduct thorough testing to verify that the cart functionality works as expected with Firestore.
   - Validate data consistency and accuracy between the old and new database systems.

4. **Performance Optimization:**
   - Optimize Firestore queries and indexing to ensure efficient performance, especially during high traffic periods.

### Additional Information
- Firestore offers several advantages over Realtime Database, including better scalability, real-time updates, and more advanced querying capabilities.
- Migrating the cart database to Firestore aligns with our goal of modernizing our infrastructure and improving the overall performance of our application.

### Priority
High

### Labels
database, migration, firestore

**Comment by MAVRICK-1** [comment]
@Hemu21 divide this issue into two part on is storing and one is retrieving

**Comment by Hemu21** [comment]
@MAVRICK-1  ok thank you for assigning. can you please add labels.

**Comment by MAVRICK-1** [comment]
@Hemu21 use uid as primary firebase will return a object after successful login, use the uid from the object as primary key

**Comment by Hemu21** [comment]
@MAVRICK-1 Part 1 of this issue is completed and i had created the pr please check.
