### ISSUE TITLE
anchor tag used without styling and browse all the catagory drop down is not woking

### ISSUE THREAD

**Issue by RamakrushnaBiswal** [MAVRICK-1/e-commerce_website#57]
**Describe the bug**

At the navbar cart the anchor tag is not styled and Browse all the category dropdown is not working
**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/125277258/d4e43850-6078-4bc8-a86d-f761fa25ba98)

video-
https://github.com/MAVRICK-1/e-commerce_website/assets/125277258/d950b2e2-f643-4643-9248-67f2c61360d0

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MAVRICK-1** [comment]
@RamakrushnaBiswal you have to logged in for that

**Comment by MAVRICK-1** [comment]
@RamakrushnaBiswal you can work with the drop down issue

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by MAVRICK-1** [comment]
@Yashc885 if did get any update from @RamakrushnaBiswal by today this will be assigned to you
