### ISSUE TITLE
Enhance the carousel

### ISSUE THREAD

**Issue by Harshitazz** [MAVRICK-1/e-commerce_website#59]
carousel enhance the overall appeal of the site.

ADD more images and make the carousel autoplay after some seconds.

adding more slides

**Comment by MAVRICK-1** [comment]
@Harshitazz let me see , if i have any more images

**Comment by Harshitazz** [comment]
@MAVRICK-1 let me know

**Comment by Yashc885** [comment]
i would like to resolve this issue

**Comment by MAVRICK-1** [comment]
@Harshitazz closing this , did found proper  carousel image , If find any you can reopen this issue
