### ISSUE TITLE
Fix Wishlist Functionality

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#6]
### Issue: Fix Wishlist Functionality

<img width="959" alt="Screenshot 2024-05-09 224606" src="https://github.com/MAVRICK-1/e-commerce_website/assets/146999057/23081339-28ec-41a2-a74d-b39a1e2032ac">

#### Description:
Currently, the wishlist functionality on our e-commerce website is not functioning. To address this, we can utilize Firestore to store wishlist data in the backend and render it on the wishlist page. The layout used for the cart page can be repurposed to display wishlist items.

#### Proposed Solution:
1. Implement Firestore integration to store wishlist data.
2. Develop functionality to add and remove items from the wishlist.
3. Modify the wishlist page layout using the [cart page](https://github.com/MAVRICK-1/e-commerce_website/tree/main/src/pages/cart) layout as a template.
4. Ensure seamless rendering of wishlist items on the wishlist page.
5. Test thoroughly to ensure proper functionality.

#### Assignee:
Firebase access will be provided for implementation.
Documentation of Firestore : [Firestore](https://firebase.google.com/docs/firestore/manage-data/add-data)

#### Labels:
- Enhancement
- Firestore
- Wishlist

**Comment by dev-rsiva** [comment]
I want to work on this. I request that you assign it to me. I think I have enough firestore experience to implement this. Let me do it.

**Comment by MAVRICK-1** [comment]
give me your email , i will give you the access

**Comment by dev-rsiva** [comment]
Email: dev.rsiva@gmail.com

**Comment by MAVRICK-1** [comment]
@dev-rsiva check your mail

**Comment by dev-rsiva** [comment]
I have received mail. Let me have a look at it by morning.

Regards,
Siva

**Comment by dev-rsiva** [comment]
> @dev-rsiva check your mail

I have received mail. Let me have a look at it by morning.

**Comment by MAVRICK-1** [comment]
@dev-rsiva any updates ? or should i pass it to @Hemu21

**Comment by dev-rsiva** [comment]
Sorry for the delayed response. I am understanding the code now. I have few query.

Why did you not having user specific data in firebase backend. I am not seeing it. I am just seeing the carts collection, seller collection only.

Whether you have any specific reason for it.

What my concern is we need to finalise how the data structure to be followed. Whether user- specific data or

Common data where each data link with the users who associated.

Have you worked on it.

**Comment by dev-rsiva** [comment]
> @dev-rsiva any updates ? or should i pass it to @Hemu21 

Sorry for the delayed response. I am understanding the code now. I have few query.

Why did you not having user specific data in firebase backend. I am not seeing it. I am just seeing the carts collection, seller collection only.

Whether you have any specific reason for it.

What my concern is we need to finalise how the data structure to be followed. Whether user- specific data or

Common data where each data link with the users who associated.

Have you worked on it.

**Comment by MAVRICK-1** [comment]
@dev-rsiva #60 will solve this one , and we get the user data from fireauth

**Comment by MAVRICK-1** [comment]
@dev-rsiva we got uid as primary key , so it is associate to it's respective users

**Comment by dev-rsiva** [comment]
> @dev-rsiva we got uid as primary key , so it is associate to it's respective users
> 

Ok let me work and complete.

**Comment by dev-rsiva** [comment]
I have worked on this task and submitted. I request you to review the pull request.

**Comment by MAVRICK-1** [comment]
closed by #94
