### ISSUE TITLE
Responsive Ui Design for about us contributors details card 

### ISSUE THREAD

**Issue by CoderSwarup** [MAVRICK-1/e-commerce_website#61]
**Is your feature request related to a problem? Please describe.**
in the about us page the in our contributors section the contributors card ui is decent where i want to update that ui in to the proper profile card and also their bug in the css where the x axis is overflow in the page 

**Describe the solution you'd like**

making an interactive card ui design with the proper contributors details  and related links 

**Describe alternatives you've considered**

**Additional context**

![Screenshot 2024-05-11 230954](https://github.com/MAVRICK-1/e-commerce_website/assets/128630311/7cd016fd-1a75-4d82-8fe2-bc571eb70d26)

see the bottom right corner where the page is overflow and get the horizontal line on it 

please assign this issue to me , i want to work on this issue

**Comment by MAVRICK-1** [comment]
@CoderSwarup this issue is already created and assigned #50
