### ISSUE TITLE
[ADDITION]: Adding more items in home page 

### ISSUE THREAD

**Issue by Dishika18** [MAVRICK-1/e-commerce_website#68]
As I can see when we open the website, in the home page most of the items are showing as "loading" which means the items hasn't been added on the website yet. Also in the Featured Category there are only 3 category added. 
I can add more items and categories in the Home page. 
Please assign me this issue under GSSoC'24.  
Thank you!

**Comment by MAVRICK-1** [comment]
@Dishika18 Thanks for it , don't you think it is time consuming , creating new items and picture if you want I can assign you that, it will be level 3
