### ISSUE TITLE
 Update About Page to Contributor Page 

### ISSUE THREAD

**Issue by MAVRICK-1** [MAVRICK-1/e-commerce_website#7]
#### Description:
Transform the About page into a Contributor page using Material UI or CSS to display contributor details fetched from the GitHub API (`https://api.github.com/repos/MAVRICK-1/e-commerce_website/contributors`). Clicking on a contributor card will redirect to their GitHub profile.

#### Proposed Solution:
1. Utilize Material UI or CSS for styling contributor cards.
2. Integrate GitHub API to fetch contributor data dynamically.
3. Design card layout to showcase contributor details.
4. Implement functionality to link contributor cards to their GitHub profiles.
5. Ensure responsiveness for optimal viewing experience.

#### Assignee:
Responsible team member with Material UI or CSS expertise will be assigned.

#### Labels:
- Enhancement
- GitHub API
- Material UI
- CSS
- Contributor Page

**Comment by tusharlikestocode** [comment]
Would like to work on this

**Comment by MAVRICK-1** [comment]
Contributor period has not started yet , first come first serve basis it
will be assign to you

**Comment by GOURAVSINGH19** [comment]
Can you assign this project to me. I want to contribute..

**Comment by tusharlikestocode** [comment]
@MAVRICK-1 please assign the issue @GOURAVSINGH19 since I won't be able to start working on it immediately
