### ISSUE TITLE
Fix location popup

### ISSUE THREAD

**Issue by jinx-vi-0** [MAVRICK-1/e-commerce_website#70]
Everytime page gets reload it asks for location acces. It should be like this, if the user cross it, it should not popup again for the user.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/120160355/9cc616ad-051e-42d0-9ba7-1d2187e824cf)

**Comment by jinx-vi-0** [comment]
hey @MAVRICK-1, please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@jinx-vi-0 okay go ahead

**Comment by mukilan2815** [comment]
@MAVRICK-1 Can i work on this?
