### ISSUE TITLE
fix cart redirect

### ISSUE THREAD

**Issue by jinx-vi-0** [MAVRICK-1/e-commerce_website#71]
Cart option on the top right corner redirects to the about us where there is info about the contributors. It should redirect to the cart.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/120160355/2e1f061f-7c39-4bd0-8a6a-f0743b0d0e6c)

hey @MAVRICK-1 , please assign this issue to me.

**Comment by Hemu21** [comment]
@jinx-vi-0  hey close this issue Why because This issue is included in #73  and I had solved it.

**Comment by jinx-vi-0** [comment]
@Hemu21 , read the issue again and then decide whether they are same or not. and let admin decide whether to close it or not.

**Comment by Hemu21** [comment]
@jinx-vi-0  I understand the issue created by you. You mentioned When user not signed in and click on cart it should redirect to signin but it is redirecting to about us page. migrating to firestore with Make sure the curd operation changes reflect on the website. It had completed.

**Comment by jinx-vi-0** [comment]
@Hemu21 so you had already implemented it but you pr has still not merged. am i right ?

**Comment by Hemu21** [comment]
@jinx-vi-0 yes.

**Comment by jinx-vi-0** [comment]
@Hemu21 ok
