### ISSUE TITLE
Update Footer section

### ISSUE THREAD

**Issue by jinx-vi-0** [MAVRICK-1/e-commerce_website#72]
Footer section contains duplicate entries and also have documental errors. The text are not properly aligned and there are some unwanted text in the footer section.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/120160355/1295b8a2-3e66-482c-9255-745386f136f0)

hey @MAVRICK-1 , please assign this issue to me.

**Comment by MAVRICK-1** [comment]
@jinx-vi-0 go ahead

**Comment by jinx-vi-0** [comment]
Hey @MAVRICK-1 , I've submitted a PR. Could you please take a look and provide any feedback you have? Thanks!

**Comment by MAVRICK-1** [comment]
Quite busy right now, will review everything after,2 days
