### ISSUE TITLE
Location. (no need for country names, Indian cities name should be there)

### ISSUE THREAD

**Issue by QQ07** [MAVRICK-1/e-commerce_website#74]
**Describe the bug**
The Location dropdown currently contains Country names in the world.

**Expected behavior**
Dropdown should have Indian cities instead

**Screenshots**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/77952121/6c5d5138-c843-49ad-bb17-94edfa4e5fc0)

Can I work on this issue under gssoc'24

**Comment by MAVRICK-1** [comment]
@QQ07 go ahead

**Comment by MAVRICK-1** [comment]
@QQ07 any updates?

**Comment by Hemu21** [comment]
@MAVRICK-1 can you please assign this to me.

**Comment by MAVRICK-1** [comment]
@Hemu21 go ahead
