### ISSUE TITLE
Bug in Sign In page

### ISSUE THREAD

**Issue by GOURAVSINGH19** [MAVRICK-1/e-commerce_website#87]
sign In page and sign In page not looking good. There is problem in texts.
If  this issue not assigned then assign me. If it is then it's Ok. 
![Screenshot 2024-05-13 104153](https://github.com/MAVRICK-1/e-commerce_website/assets/120244528/869b67a9-16e1-41b9-ab0a-85ecabd1816d)
![Screenshot 2024-05-13 104142](https://github.com/MAVRICK-1/e-commerce_website/assets/120244528/6d4e69df-d78a-452f-9927-94ccb5ffc288)

**Comment by GOURAVSINGH19** [comment]
@MAVRICK-1

**Comment by MAVRICK-1** [comment]
@GOURAVSINGH19 okay go ahead try to solve both sign in and signup in a single issue

**Comment by GOURAVSINGH19** [comment]
@MAVRICK-1  I already solve this in #107 issue
