### ISSUE TITLE
[DOC-BUG] :Mistake-IN- READme.md.

### ISSUE THREAD

**Issue by anglerfishlyy** [MAVRICK-1/e-commerce_website#92]
**Describe the bug**
There is a mistake in Readme.md document.

**To Reproduce**

1. Go to Readme.md
2. Scroll down to contributing guidelines section.
3. The second most important step after forking is missing.

**Screenshots**

![Screenshot (53)](https://github.com/MAVRICK-1/e-commerce_website/assets/163823908/41e847f1-8d95-433f-8119-7cb605469ca5)

**Comment by anglerfishlyy** [comment]
can you assign me this under gssoc?

**Comment by MAVRICK-1** [comment]
@anglerfishlyy  Look under the contribution heading it's already give
