### ISSUE TITLE
Adding pre-commit hooks

### ISSUE THREAD

**Issue by AvdhutPailwan** [MAVRICK-1/e-commerce_website#93]
In the project there is no linting like prettier or eslint which can make the code styling inconsistent which causes difficulty for maintainance of the project. I would like add linting as well pre-commit hooks to the which will force the consistent styling to the project before every commit.

@MAVRICK-1 Please assign this issue to me under gssoc 2024

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan you can start your work after merging this #69 PR

**Comment by MAVRICK-1** [comment]
@AvdhutPailwan go ahead

**Comment by AvdhutPailwan** [comment]
@MAVRICK-1 should I do the changes by forking main branch or dev branch?

**Comment by AvdhutPailwan** [comment]
> @MAVRICK-1 should I do the changes by forking main branch or dev branch?

I'll fork the main branch and will work on it. If you suggest i'll make the necessary changes accordingly

**Comment by AvdhutPailwan** [comment]
> @AvdhutPailwan make the changes in dev branch

okay

**Comment by AvdhutPailwan** [comment]
@MAVRICK-1 I am done please check when you get time and merge the changes
