### ISSUE TITLE
Redirect to dialer

### ISSUE THREAD

**Issue by pankaj-bind** [MAVRICK-1/e-commerce_website#95]
**Is your feature request related to a problem? Please describe.**
When user click on the given phone number it will redirect them to their phone's dialer pad.

**Describe the solution you'd like**
I will write a script so that when user clicks on given phone number it will redirect him to dialer pad.

**Additional context**
Assign me this work under GSSoC24, I'll implement it.

![image](https://github.com/MAVRICK-1/e-commerce_website/assets/73558583/24194ac2-a94f-4557-b475-357a52adae03)

**Comment by MAVRICK-1** [comment]
@pankaj-bind #77  duplicate issue
