### ISSUE TITLE
Redirect to email

### ISSUE THREAD

**Issue by pankaj-bind** [MAVRICK-1/e-commerce_website#96]
**Is your feature request related to a problem? Please describe.**
When user click on the given email it will redirect them to their email-box.

**Describe the solution you'd like**
I will write a script so that when user clicks on given email it will redirect him to email-box.

**Additional context**
Assign me this work under GSSoC24, I'll implement it.

**Additional context**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/73558583/532a3bac-5264-4e4b-bedc-9e87dc8adcdd)

**Comment by MAVRICK-1** [comment]
@pankaj-bind #77  duplicate issue
