### ISSUE TITLE
Redirect to Google Map

### ISSUE THREAD

**Issue by pankaj-bind** [MAVRICK-1/e-commerce_website#97]
**Is your feature request related to a problem? Please describe.**
When user click on the given location it will redirect them to their map.

**Describe the solution you'd like**
I will write a script so that when user clicks on given location it will redirect them to map.

**Additional context**
Assign me this work under GSSoC24, I'll implement it.

**Additional context**
![image](https://github.com/MAVRICK-1/e-commerce_website/assets/73558583/86188b21-d9f8-4066-aa28-ce6c9c7f447b)

**Comment by MAVRICK-1** [comment]
@pankaj-bind okay go ahead i will assign the label after see your PR

**Comment by Hemu21** [comment]
@MAVRICK-1  can you please assign this to me

**Comment by MAVRICK-1** [comment]
@Hemu21 okay go ahead
