### ISSUE TITLE
Bug in slider

### ISSUE THREAD

**Issue by pankaj-bind** [MAVRICK-1/e-commerce_website#98]
**Describe the bug**
Slider showing unwanted behavior. Even when curser not on that it still sliding.

**To Reproduce**
I will improve its code. To make sure it works only when user slides on it.

1. Go to '[link](https://nestondc.vercel.app/cat/electronics/tv-&-speaker#/cat/electronics)'
2. See error

**Expected behavior**
It should work only when user slides curser on it.

**Screenshots**

https://github.com/MAVRICK-1/e-commerce_website/assets/73558583/36a88284-a8ea-4c32-9539-2f64c324da9e

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser Microsoft Edge
- Version 124.0.2478.97

**Smartphone (please complete the following information):**

**Additional context**
Assign me this work under GSSoC24, I will fix it.

**Comment by MAVRICK-1** [comment]
@pankaj-bind 
go ahead and fix it and  slider position must be like this [Link](https://nestondc.el.r.appspot.com/#/cat/electronics)

**Comment by MAVRICK-1** [comment]
closed by #114
